use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, strum::Display, clap::ValueEnum, Default)]
#[serde(rename_all = "camelCase")]
pub enum CommandName {
    Init,
    Absorb,
    Status,
    Stf,
    Rub,
    Diff,
    Squash,
    Commit,
    Push,
    New,
    Describe,
    OplogList,
    OplogSnapshot,
    Restore,
    Undo,
    Gui,
    BaseFetch,
    BaseCheck,
    Pull,
    BranchNew,
    BranchDelete,
    BranchList,
    BranchShow,
    BranchUnapply,
    BranchApply,
    ClaudePreTool,
    ClaudePostTool,
    ClaudeStop,
    CursorAfterEdit,
    CursorStop,
    Worktree,
    Mark,
    Unmark,
    ForgeAuth,
    ForgeListUsers,
    ForgeForget,
    PrNew,
    PrTemplate,
    Completions,
    #[default]
    Unknown,
}
