//! CLI ID generation and mapping for GitButler entities.
//!
//! This module provides a system for generating short, human-friendly IDs for various GitButler
//! entities including branches, commits, and files. These IDs are used in the CLI to make commands
//! more convenient and readable than using full SHA-1 hashes or long branch names.

#![forbid(missing_docs)]

use std::{
    borrow::Borrow,
    collections::{BTreeMap, BTreeSet, HashMap},
};

use crate::id::{
    file_info::FileInfo,
    id_usage::{IdUsage, UintId},
    stacks_info::StacksInfo,
};
use bstr::{BStr, BString, ByteSlice};
use but_core::ref_metadata::StackId;
use but_ctx::Context;
use but_hunk_assignment::HunkAssignment;
use but_workspace::branch::Stack;
use nonempty::NonEmpty;

mod file_info;
mod id_usage;
mod stacks_info;

#[cfg(test)]
mod tests;

/// A helper to indicate that this is a short-id as a user would see.
type ShortId = String;

/// A mapping from user-friendly CLI IDs to GitButler entities.
///
/// # Lifecycle
///
/// 1. Create an `IdMap` for example using [IdMap::new_for_branches_and_commits]
/// 2. Optionally add file information for example using [IdMap::add_file_info_from_context]
/// 3. Use [IdMap::resolve_entity_to_ids] to parse user input into matching IDs
/// 4. Use specific methods like [IdMap::resolve_branch]
///    or [IdMap::resolve_file_changed_in_commit_or_unassigned] to get IDs for specific entities
#[derive(Debug)]
pub struct IdMap {
    /// Maps shortened branch names to their assigned CLI IDs
    branch_name_to_cli_id: BTreeMap<BString, CliId>,
    /// Maps [ShortId]s of branches if they are autogenerated to CLI IDs.
    /// This will be duplicate at least in parts with `branch_name_to_cli_id`.
    branch_auto_id_to_cli_id: HashMap<ShortId, CliId>,
    /// Tracks all non-commit IDs that have been used to avoid collisions.
    /// Needed when adding more IDs to know which one is next.
    id_usage: IdUsage,
    /// Commit IDs reachable from workspace tips with their first parent IDs
    workspace_commit_and_first_parent_ids: Vec<(gix::ObjectId, Option<gix::ObjectId>)>,
    /// Commit IDs that are only on the remote
    remote_commit_ids: Vec<gix::ObjectId>,
    /// The ID representing the unassigned area, i.e. uncommitted files that aren't assigned to a stack.
    unassigned: CliId,

    /// Uncommitted files in a mapping from generated `ShortID`s to its file information.
    /// It's public for convenience in `but rub` currently.
    pub uncommitted_files: BTreeMap<ShortId, UncommittedFile>,
    /// Uncommitted hunks.
    uncommitted_hunks: HashMap<ShortId, UncommittedHunk>,
    /// Committed files with their assigned IDs
    committed_files: BTreeSet<CommittedFile>,
}

/// Lifecycle methods for creating and initializing `IdMap` instances.
impl IdMap {
    /// Initializes CLI IDs for all *branches* and *commits* in the given `stacks`.
    ///
    /// This method creates a new `IdMap` with IDs for branches and commits only.
    /// To enable parsing of file IDs, call [IdMap::add_file_info_from_context]
    pub fn new_for_branches_and_commits(stacks: &[Stack]) -> anyhow::Result<Self> {
        let StacksInfo {
            branch_names,
            workspace_commit_and_first_parent_ids,
            remote_commit_ids,
        } = StacksInfo::from_stacks(stacks)?;

        let mut max_zero_count = 1; // Ensure at least two "0" in ID.
        for branch_name in &branch_names {
            for field in branch_name.fields_with(|c| c != '0') {
                max_zero_count = std::cmp::max(field.len(), max_zero_count);
            }
        }
        let (id_usage, branch_name_to_cli_id, branch_auto_id_to_cli_id) =
            Self::ids_for_branch_names(branch_names)?;
        Ok(Self {
            branch_name_to_cli_id,
            branch_auto_id_to_cli_id,
            id_usage,
            workspace_commit_and_first_parent_ids,
            remote_commit_ids,
            unassigned: CliId::Unassigned {
                id: str::repeat("0", max_zero_count + 1),
            },
            uncommitted_files: BTreeMap::new(),
            uncommitted_hunks: HashMap::new(),
            committed_files: BTreeSet::new(),
        })
    }

    /// Scan short `branch_names` in windows of 2 to 3 (presumed) ascii characters and see if
    /// they resemble [`UintId`]s. If so, use them, otherwise, see if they can be used unambiguously
    /// directly. If not, generate an ID.
    #[allow(clippy::type_complexity)]
    fn ids_for_branch_names(
        branch_names: Vec<BString>,
    ) -> anyhow::Result<(IdUsage, BTreeMap<BString, CliId>, HashMap<ShortId, CliId>)> {
        // Extract all valid short-ids that are contained in branch names
        // to see if they are unique.
        let mut short_ids_to_count: HashMap<ShortId, u8> = HashMap::new();
        let mut id_usage = IdUsage::default();
        for branch_name in &branch_names {
            for candidate in branch_name.windows(2).chain(branch_name.windows(3)) {
                if let Some(short_id) = UintId::from_name(candidate)
                    .map(|uint_id| {
                        id_usage.mark_used(uint_id);
                        uint_id.to_short_id()
                    })
                    .or_else(|| {
                        // If it's not a valid UintId, it's still acceptable if it
                        // cannot be confused for a commit ID (and is valid UTF-8).
                        if candidate.iter().all(|c| c.is_ascii_alphanumeric())
                            && !candidate.iter().all(|c| c.is_ascii_hexdigit())
                        {
                            String::from_utf8(candidate.to_vec()).ok()
                        } else {
                            None
                        }
                    })
                {
                    short_ids_to_count
                        .entry(short_id)
                        .and_modify(|count| *count = count.saturating_add(1))
                        .or_insert(1);
                }
            }
        }

        let mut branch_name_to_cli_id: BTreeMap<BString, CliId> = BTreeMap::new();
        let mut branch_auto_id_to_cli_id: HashMap<ShortId, CliId> = HashMap::new();
        for branch_name in branch_names {
            let id = 'short_id: {
                // Find first non-conflicting pair or triple (i.e. used in
                // exactly one branch) and use it as CliId.
                for candidate in branch_name.windows(2).chain(branch_name.windows(3)) {
                    if let Ok(short_id) = str::from_utf8(candidate)
                        && let Some(1) = short_ids_to_count.get(short_id)
                    {
                        break 'short_id short_id.to_owned();
                    }
                }
                // If none available, use next available ID. Also add it to
                // `branch_auto_id_to_cli_id`, because the ID is not a substring
                // of the branch name (so we cannot find the branch just by a
                // substring search on the branch name).
                let id = id_usage.next_available()?.to_short_id();
                branch_auto_id_to_cli_id.insert(
                    id.clone(),
                    CliId::Branch {
                        name: branch_name.to_string(),
                        id: id.clone(),
                    },
                );
                // The id also needs to be assigned to the name-to-id map.
                id
            };
            let name = branch_name.to_string();
            branch_name_to_cli_id.insert(branch_name, CliId::Branch { name, id });
        }
        Ok((id_usage, branch_name_to_cli_id, branch_auto_id_to_cli_id))
    }

    /// Creates a new instance from `ctx` for more convenience over calling [IdMap::new_for_branches_and_commits].
    pub fn new_from_context(ctx: &Context) -> anyhow::Result<Self> {
        let guard = ctx.shared_worktree_access();
        let meta = ctx.meta(guard.read_permission())?;
        let repo = &*ctx.repo.get()?;
        let head_info = but_workspace::head_info(
            repo,
            &meta,
            but_workspace::ref_info::Options {
                expensive_commit_info: false,
                ..Default::default()
            },
        )?;
        Self::new_for_branches_and_commits(&head_info.stacks)
    }
}

/// Methods for adding context to enable file ID generation for the entities it contains.
impl IdMap {
    /// Adds file information from a `ctx` to add IDs for changed files in the worktree with their stack assignments
    /// and all changed files of all workspace commits.
    ///
    /// After calling this method, [IdMap::resolve_entity_to_ids] will be able to recognize file IDs in addition to branch and commit IDs.
    pub fn add_file_info_from_context(
        &mut self,
        ctx: &mut Context,
        assignments: Option<Vec<HunkAssignment>>,
    ) -> anyhow::Result<()> {
        let hunk_assignments = match assignments {
            Some(assignments) => assignments,
            None => {
                if let Some(worktree_dir) = ctx.workdir()? {
                    let changes =
                        but_core::diff::ui::worktree_changes_by_worktree_dir(worktree_dir)?.changes;
                    let (assignments, _) = but_hunk_assignment::assignments_with_fallback(
                        ctx,
                        false,
                        Some(changes),
                        None,
                    )?;
                    assignments
                } else {
                    Vec::new()
                }
            }
        };
        // TODO Fix this, probably by making `assignments_with_fallback` take a
        //      more specific type instead of `ctx`.
        let repo = &*ctx.repo.get()?;
        self.add_file_info(
            |commit_id, parent_id| {
                let tree_changes = but_core::diff::tree_changes(repo, parent_id, commit_id)?;
                Ok(tree_changes
                    .into_iter()
                    .map(|tree_change| tree_change.path)
                    .collect::<Vec<_>>())
            },
            hunk_assignments,
        )
    }

    /// Trigger the generation of IDs for uncommitted and committed files and store them in the map.
    ///
    /// It generates unique 2-character hash-based IDs for each file, ensuring no collisions with existing branch
    /// and commit IDs.
    ///
    /// * `changed_paths_in_commit_fn(commit, parent)` returns the changed file paths for a given commit
    ///   and its parent. Used to identify all files altered by workspace commits.
    /// * `hunk_assignments` - The list of uncommitted files in the worktree with their stack assignments
    fn add_file_info<F>(
        &mut self,
        changed_paths_in_commit_fn: F,
        hunk_assignments: Vec<HunkAssignment>,
    ) -> anyhow::Result<()>
    where
        F: FnMut(gix::ObjectId, Option<gix::ObjectId>) -> anyhow::Result<Vec<BString>>,
    {
        let FileInfo {
            uncommitted_files,
            committed_files,
        } = FileInfo::from_workspace_commits_and_status(
            &self.workspace_commit_and_first_parent_ids,
            changed_paths_in_commit_fn,
            &hunk_assignments,
        )?;

        for hunk_assignments in uncommitted_files.into_iter() {
            self.uncommitted_files.insert(
                self.id_usage.next_available()?.to_short_id(),
                UncommittedFile { hunk_assignments },
            );
        }
        for commit_oid_path in committed_files.into_iter() {
            self.committed_files.insert(CommittedFile {
                commit_oid_path,
                id: self.id_usage.next_available()?.to_short_id(),
            });
        }

        for uncommitted_file in self.uncommitted_files.values() {
            if !uncommitted_file.hunk_assignments.is_empty() {
                for hunk_assignment in uncommitted_file.hunk_assignments.iter() {
                    self.uncommitted_hunks.insert(
                        self.id_usage.next_available()?.to_short_id(),
                        UncommittedHunk {
                            hunk_assignment: hunk_assignment.clone(),
                        },
                    );
                }
            }
        }

        Ok(())
    }
}

/// Methods for parsing and generating CLI IDs.
impl IdMap {
    /// Parses a user-provided `entity` name into matching CLI IDs, with each ID matching a single entity.
    /// Multiple IDs may be returned if the entity matches multiple items.
    pub fn resolve_entity_to_ids(&self, entity: &str) -> anyhow::Result<Vec<CliId>> {
        // If a branch matches exactly, use only that.
        if let Some((_, cli_id)) = self
            .branch_name_to_cli_id
            .iter()
            .find(|(branch_name, _)| *branch_name == entity)
        {
            return Ok(vec![cli_id.clone()]);
        }

        if entity.len() < 2 {
            return Err(anyhow::anyhow!(
                "Id needs to be at least 2 characters long: '{entity}'"
            ));
        }

        let mut matches = Vec::<CliId>::new();

        // First, try partial branch name match
        matches.extend(
            self.find_branches_by_substring_match(entity.into())
                .map(Clone::clone),
        );

        // Only try SHA matching if the input looks like a hex string
        if entity
            .chars()
            .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase())
            && let Ok(prefix) = gix::hash::Prefix::from_hex_nonempty(entity)
        {
            for oid in self
                .workspace_and_remote_commit_ids()
                .filter(|oid| prefix.cmp_oid(oid).is_eq())
            {
                matches.push(CliId::Commit(*oid));
            }
        }

        // Then try CliId matching
        if let Some(cli_id) = self.branch_auto_id_to_cli_id.get(entity) {
            matches.push(cli_id.clone());
        }
        if let Some(uncommitted_file) = self.uncommitted_files.get(entity) {
            matches.push(uncommitted_file.to_cli_id(entity.to_owned()));
        }
        if let Some(CommittedFile {
            commit_oid_path: (commit_oid, path),
            ..
        }) = self.committed_files.get(entity)
        {
            matches.push(CliId::CommittedFile {
                commit_id: *commit_oid,
                path: path.to_owned(),
                id: entity.to_string(),
            });
        }
        if let Some(uncommitted_hunk) = self.uncommitted_hunks.get(entity) {
            matches.push(CliId::Uncommitted(UncommittedCliId {
                id: entity.to_string(),
                hunk_assignments: NonEmpty::new(uncommitted_hunk.hunk_assignment.clone()),
                is_entire_file: false,
            }));
        }
        if entity.bytes().all(|c| c == b'0') {
            matches.push(self.unassigned.clone());
        }

        Ok(matches)
    }

    /// Returns the [`CliId::CommittedFile`] for a changed file at repo-relative `path`
    /// that is contained in the `commit_id`.
    /// Note that the returned short id may be `00` as fallback if it wasn't
    /// added by [IdMap::add_file_info_from_context].
    pub fn resolve_file_changed_in_commit_or_unassigned(
        &self,
        commit_id: gix::ObjectId,
        path: &BStr,
    ) -> CliId {
        let sought = (commit_id, path.to_owned());
        if let Some(CommittedFile { id, .. }) = self.committed_files.get(&sought) {
            CliId::CommittedFile {
                commit_id: sought.0,
                path: sought.1,
                id: id.to_string(),
            }
        } else {
            CliId::CommittedFile {
                commit_id: sought.0,
                path: sought.1,
                id: "00".to_string(),
            }
        }
    }

    /// Returns the [`CliId::Branch`] for a branch by its short `name`.
    ///
    /// If the branch already has an assigned ID, return it. Otherwise, returns
    /// `00` as fallback.
    pub fn resolve_branch(&self, name: &BStr) -> CliId {
        self.branch_name_to_cli_id
            .get(name)
            .cloned()
            .unwrap_or_else(|| CliId::Branch {
                name: name.to_string(),
                id: "00".to_string(),
            })
    }

    /// Returns the [`CliId::Uncommitted`] for a given hunk assignment, if it exists.
    ///
    /// Searches for a matching hunk assignment in the uncommitted hunks map and returns
    /// its corresponding CLI ID if found.
    pub fn resolve_uncommitted_hunk(&self, hunk: &HunkAssignment) -> Option<CliId> {
        self.uncommitted_hunks.iter().find_map(|(id, uh)| {
            (uh.hunk_assignment == *hunk).then(|| {
                CliId::Uncommitted(UncommittedCliId {
                    id: id.clone(),
                    hunk_assignments: NonEmpty::new(hunk.clone()),
                    is_entire_file: false, // TODO: figure out if we can know this here
                })
            })
        })
    }

    /// Returns the [`CliId::Unassigned`] for the unassigned area, which is useful as an
    /// ID for a destination of operations.
    ///
    /// The unassigned area represents files and changes that are not assigned to any branch.
    /// Its ID is a string of repeated '0' characters, with enough repetitions to ensure
    /// it doesn't collide with any existing branch name.
    pub fn unassigned(&self) -> &CliId {
        &self.unassigned
    }
}

/// Private helper methods for `IdMap`.
impl IdMap {
    /// Finds all branches whose names contain the given `substring`.
    ///
    /// A vector of [`CliId::Branch`] instances for all matching branches.
    fn find_branches_by_substring_match<'a, 's: 'a>(
        &'s self,
        substring: &'a BStr,
    ) -> impl Iterator<Item = &'s CliId> {
        self.branch_name_to_cli_id
            .iter()
            .filter_map(move |(branch_name, cli_id)| {
                branch_name.contains_str(substring).then_some(cli_id)
            })
    }

    /// Returns an iterator over all commit IDs (workspace and remote) known to
    /// this ID map.
    fn workspace_and_remote_commit_ids(&self) -> impl Iterator<Item = &gix::ObjectId> {
        self.workspace_commit_and_first_parent_ids
            .iter()
            .map(|(commit_id, _parent_id)| commit_id)
            .chain(&self.remote_commit_ids)
    }
}

/// An uncommitted file or hunk in the worktree.
#[derive(Debug, Clone)]
pub struct UncommittedCliId {
    /// The short CLI ID for this file (typically 2 characters)
    pub id: ShortId,
    /// The hunk assignments
    pub hunk_assignments: NonEmpty<HunkAssignment>,
    /// `true` if self represents all hunks in a stack-assignment or file pair.
    /// Note that this file may have hunks with other stack assignments.
    pub is_entire_file: bool,
}

impl UncommittedCliId {
    /// Describes self.
    pub fn describe(&self) -> String {
        let hunk_cardinality = if self.is_entire_file {
            if self.hunk_assignments.len() == 1 {
                "the only hunk"
            } else {
                "all hunks"
            }
        } else {
            "a hunk"
        };
        let assignment = if self.hunk_assignments.first().stack_id.is_some() {
            "a stack"
        } else {
            "the unassigned area"
        };
        format!(
            "{hunk_cardinality} in {} in {assignment}",
            self.hunk_assignments.first().path_bytes,
        )
    }
}

/// A user-friendly CLI ID that identifies a GitButler entity,
/// with each identified by a variant.
///
/// This enum represents the various types of entities that can be identified
/// by short CLI IDs. Each variant contains the necessary information to
/// uniquely identify the entity along with its short ID that one could use
/// to find it.
#[derive(Debug, Clone)]
pub enum CliId {
    /// An uncommitted file or hunk in the worktree.
    Uncommitted(UncommittedCliId),
    /// A file that exists in a commit.
    CommittedFile {
        /// The object ID of the commit containing the change to the file
        commit_id: gix::ObjectId,
        /// The file path relative to the repository root
        path: BString,
        /// The short CLI ID for this file (typically 2 characters)
        id: ShortId,
    },
    /// A branch.
    Branch {
        /// The short name of the branch, like `main` or `origin/feat`.
        name: String,
        /// The short CLI ID for this branch (typically 2 characters)
        id: ShortId,
    },
    /// A commit in the workspace identified by its SHA.
    // TODO: Ensure our prefixes are unique within the set of known commits,
    //       currently we only take the first two characters which can clash
    //       without us noticing. See commit_ids_are_currently_ambiguous() test.
    Commit(gix::ObjectId),
    /// The unassigned area, as a designated area that files can be put in.
    Unassigned {
        /// The CLI ID for the unassigned area (a string of 2 or more zeros).
        id: ShortId,
    },
}
impl PartialEq for CliId {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (
                Self::Uncommitted(UncommittedCliId { id: l_id, .. }),
                Self::Uncommitted(UncommittedCliId { id: r_id, .. }),
            ) => l_id == r_id,
            (Self::CommittedFile { id: l_id, .. }, Self::CommittedFile { id: r_id, .. }) => {
                l_id == r_id
            }
            (Self::Branch { id: l_id, .. }, Self::Branch { id: r_id, .. }) => l_id == r_id,
            (Self::Commit(l0), Self::Commit(r0)) => l0 == r0,
            (Self::Unassigned { .. }, Self::Unassigned { .. }) => true,
            _ => false,
        }
    }
}
impl Eq for CliId {}

/// Methods for accessing `CliId` information.
impl CliId {
    /// Returns a human-readable description of the entity type.
    pub fn kind_for_humans(&self) -> &'static str {
        match self {
            CliId::Uncommitted { .. } => "an uncommitted file or hunk",
            CliId::CommittedFile { .. } => "a committed file",
            CliId::Branch { .. } => "a branch",
            CliId::Commit { .. } => "a commit",
            CliId::Unassigned { .. } => "the unassigned area",
        }
    }

    /// Returns the short ID string for display to users.
    pub fn to_short_string(&self) -> ShortId {
        match self {
            CliId::Uncommitted(UncommittedCliId { id, .. })
            | CliId::CommittedFile { id, .. }
            | CliId::Branch { id, .. }
            | CliId::Unassigned { id, .. } => id.clone(),
            // TODO: make this so we can't display prefixes that are ambiguous.
            CliId::Commit(oid) => oid.to_hex_with_len(2).to_string(),
        }
    }
}

/// Internal representation of an uncommitted file.
#[derive(Debug, Clone)]
pub struct UncommittedFile {
    /// Every element has the same [HunkAssignment::stack_id] and [HunkAssignment::path_bytes],
    /// so the first assignment can be used to obtain both.
    pub hunk_assignments: NonEmpty<HunkAssignment>,
}

impl UncommittedFile {
    /// Return the file's stack if it is associated to one, or `None` if the Stack is unknown/has no ID.
    pub fn stack_id(&self) -> Option<StackId> {
        self.hunk_assignments.first().stack_id
    }
    /// The path of the uncommitted file.
    pub fn path(&self) -> &BStr {
        self.hunk_assignments.first().path_bytes.as_ref()
    }
    /// Turn this instance into a [CliId], using `id` for identification.
    pub fn to_cli_id(&self, id: ShortId) -> CliId {
        CliId::Uncommitted(UncommittedCliId {
            hunk_assignments: self.hunk_assignments.clone(),
            id,
            is_entire_file: true,
        })
    }
}

/// Internal representation of a committed file with its CLI ID.
///
/// This structure is used to store committed files in a `BTreeSet` where ordering
/// and equality are determined solely by the `commit_oid_path` field, enabling
/// deduplication and efficient lookups by (commit_oid, path) tuple.
#[derive(Debug)]
struct CommittedFile {
    /// The file's commit object ID and path
    commit_oid_path: (gix::ObjectId, BString),
    /// The short CLI ID assigned to this file
    id: ShortId,
}

impl PartialEq for CommittedFile {
    fn eq(&self, other: &Self) -> bool {
        self.commit_oid_path == other.commit_oid_path
    }
}

impl Eq for CommittedFile {}

impl PartialOrd for CommittedFile {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for CommittedFile {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.commit_oid_path.cmp(&other.commit_oid_path)
    }
}

impl Borrow<(gix::ObjectId, BString)> for CommittedFile {
    fn borrow(&self) -> &(gix::ObjectId, BString) {
        &self.commit_oid_path
    }
}
impl Borrow<str> for CommittedFile {
    fn borrow(&self) -> &str {
        &self.id
    }
}

#[derive(Debug)]
struct UncommittedHunk {
    hunk_assignment: HunkAssignment,
}
