packages:
  - apps/*
  - packages/*
  - crates/*
  - e2e

engineStrict: true
autoInstallPeers: true
nodeLinker: isolated

allowBuilds:
  "@ffmpeg-installer/darwin-arm64": true
  "@ffmpeg-installer/darwin-x64": true
  "@ffmpeg-installer/linux-arm": true
  "@ffmpeg-installer/linux-arm64": true
  "@ffmpeg-installer/linux-ia32": true
  "@ffmpeg-installer/linux-x64": true
  "@ffmpeg-installer/win32-ia32": true
  "@ffmpeg-installer/win32-x64": true
  "@prisma/client": true
  core-js: true
  electron: true
  electron-winstaller: true
  "@parcel/watcher": false
  "@posthog/cli": false
  "@sentry/cli": false
  edgedriver: false
  esbuild: false
  geckodriver: false
  leveldown: false
  playwright-webkit: false
  unrs-resolver: false

catalog:
  "@playwright/test": 1.58.2
  "@vitest/browser": 3.2.7
  "@vitest/ui": 3.2.4
  marked: 15.0.12
  playwright: 1.58.2
  playwright-webkit: 1.58.2
  rxjs: 7.8.2
  typescript: 5.9.3
  vite: 6.4.3
  vitest: 3.2.6

catalogs:
  postcss:
    "@types/postcss-pxtorem": 6.1.0
    postcss: 8.5.23
    postcss-cli: 11.0.1
    postcss-custom-media: 11.0.6
    postcss-load-config: 5.1.0
    postcss-nesting: 12.1.5
    postcss-pxtorem: 6.1.0
  redux:
    "@reduxjs/toolkit": 2.11.2
  svelte:
    "@sentry/sveltekit": 10.44.0
    "@sveltejs/adapter-static": 3.0.10
    "@sveltejs/kit": 2.52.2
    "@sveltejs/package": 2.5.7
    "@sveltejs/vite-plugin-svelte": 6.2.4
    svelte: 5.54.0
    svelte-check: 4.4.5

overrides:
  "@hono/node-server": 2.0.10
  "@modelcontextprotocol/sdk>@hono/node-server": 2.0.10
  ajv@6.12.6: 6.14.0
  axios: 1.13.5
  devalue: 5.6.3
  diff@^4.0.0: 4.0.4
  diff@^5.0.0: 5.2.2
  diff@^8.0.0: 8.0.3
  fast-xml-parser: 5.3.7
  "@isaacs/brace-expansion": 5.0.1
  lodash: 4.17.23
  lodash-es: 4.17.23
  minimatch@^10.0.0: 10.2.2
  qs: 6.15.2
  undici@6.22.0: 6.23.0
  "@lexical/clipboard": 0.27.2
  "@lexical/code": 0.27.2
  "@lexical/file": 0.27.2
  "@lexical/hashtag": 0.27.2
  "@lexical/history": 0.27.2
  "@lexical/html": 0.27.2
  "@lexical/link": 0.27.2
  "@lexical/list": 0.27.2
  "@lexical/mark": 0.27.2
  "@lexical/markdown": 0.27.2
  "@lexical/offset": 0.27.2
  "@lexical/overflow": 0.27.2
  "@lexical/plain-text": 0.27.2
  "@lexical/rich-text": 0.27.2
  "@lexical/selection": 0.27.2
  "@lexical/table": 0.27.2
  "@lexical/text": 0.27.2
  "@lexical/utils": 0.27.2
  "@lexical/yjs": 0.27.2
  lexical: 0.27.2

# Don't allow package versions less than two days old to be installed.
# https://pnpm.io/settings#minimumreleaseage
# Packages can be exclude from this setting with the `minimumReleaseAgeExclude` property.
minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "@gitbutler/design-core"
  - "@modelcontextprotocol/sdk"
