export enum TestId {
	BranchNameLabel = 'branch-name-label',
	BranchHeader = 'branch-header',
	BranchHeaderContextMenu = 'branch-header-context-menu',
	BranchHeaderContextMenu_AddDependentBranch = 'branch-header-context-menu-add-dependent-branch',
	BranchHeaderContextMenu_OpenInBrowser = 'branch-header-context-menu-open-in-browser',
	BranchHeaderContextMenu_CopyBranchName = 'branch-header-context-menu-copy-branch-name',
	BranchHeaderContextMenu_AddRemoveDescription = 'branch-header-context-menu-add-remove-description',
	BranchHeaderContextMenu_GenerateBranchName = 'branch-header-context-menu-generate-branch-name',
	BranchHeaderContextMenu_Rename = 'branch-header-context-menu-rename',
	BranchHeaderContextMenu_Delete = 'branch-header-context-menu-delete',
	BranchHeaderContextMenu_OpenPRInBrowser = 'branch-header-context-menu-open-pr-in-browser',
	BranchHeaderContextMenu_CopyPRLink = 'branch-header-context-menu-copy-pr-link',
	BranchHeaderRenameModal = 'branch-header-rename-modal',
	BranchHeaderRenameModal_Warning = 'branch-header-rename-modal-warning',
	BranchHeaderContextMenu_SquashAllCommits = 'branch-header-context-menu-squash-all-commits',
	EditCommitMessageDrawer = 'edit-commit-message-drawer',
	CommitDrawer = 'commit-drawer',
	CommitDrawerActionUncommit = 'commit-drawer-action-uncommit',
	CommitDrawerActionEditMessage = 'commit-drawer-action-edit-message',
	CommitDrawerTitleInput = 'commit-drawer-title-input',
	CommitDrawerDescriptionInput = 'commit-drawer-description-input',
	CommitDrawerActionButton = 'commit-drawer-action-button',
	CommitDrawerTitle = 'commit-drawer-title',
	CommitDrawerDescription = 'commit-drawer-description',
	UncommittedChanges_FileList = 'uncommitted-changes-file-list',
	FileListItem = 'file-list-item',
	UncommittedChanges_Header = 'uncommitted-changes-header',
	StartCommitButton = 'start-commit-button',
	CommitRow = 'commit-row',
	CommitRowContextMenu = 'commit-row-context-menu',
	CommitRowContextMenu_UncommitMenuButton = 'commit-row-context-menu-uncommit-menu-btn',
	CommitRowContextMenu_EditMessageMenuButton = 'commit-row-context-menu-edit-message-menu-btn',
	NewCommitDrawer = 'new-commit-drawer',
	StackDraft = 'stack-draft',
	YourCommitGoesHere = 'your-commit-goes-here',
	KebabMenuButton = 'kebab-menu-btn',
	IntegrateUpstreamCommitsButton = 'integrate-upstream-commits-button',
	IntegrateUpstreamCommitsModal = 'integrate-upstream-commits-modal',
	IntegrateUpstreamSeriesRow = 'integrate-upstream-series-row',
	IntegrateUpstreamActionButton = 'integrate-upstream-action-button',
	FileListModeOption = 'file-list-mode-option',
	FileListTreeFolder = 'file-list-tree-folder',
	StackTab = 'stack-tab',
	BranchChangedFileList = 'branch-changed-file-list',
	UnifiedDiffView = 'unified-diff-view',
	UnifiedDiffViewLockWarning = 'unified-diff-view-lock-warning',
	ToastInfoMessage = 'toast-info-message',
	Stack = 'stack',
	StackHeader = 'stack-header'
}

export enum ElementId {
	NewBranchNameInput = 'new-branch-name-input'
}
