//! GitButler Node.js SDK
//!
//! This crate generates Node.js bindings for GitButler's Rust APIs via napi-rs.
//! It exposes the same functionality available in the `but-api` crate to JavaScript/TypeScript
//! applications like Electron.
//!
//! The actual napi functions are auto-generated by the `#[but_api]` proc macro in the
//! `but-api` crate and pulled in via the `napi-auto` feature (which enables `but-api/napi`).
//! This crate serves as the `cdylib` target that napi-rs needs to produce the `.node` binary.

#![deny(clippy::all)]

// Force but-api to be linked so napi-rs discovers its #[napi] functions.
use but_api as _;
