//! App-level settings functions.
//!
//! These are handwritten rather than generated by the `#[but_api]` macro
//! because the macro only injects project-scoped `Context` state, while
//! settings are app-scoped.

use std::sync::Mutex;

use but_settings::AppSettingsWithDiskSync;
use napi_derive::napi;

use crate::{app_settings_sync, to_napi_err};

/// Serializes settings updates within this process. Each update loads a fresh
/// snapshot from disk (so changes from other processes are picked up), but
/// saving diffs that snapshot against the disk state — without the lock, two
/// concurrent updates could each diff against the other's unsaved state and
/// revert it.
static UPDATE_LOCK: Mutex<()> = Mutex::new(());

fn locked_update(
    apply: impl FnOnce(&AppSettingsWithDiskSync) -> anyhow::Result<()>,
) -> napi::Result<()> {
    let _guard = UPDATE_LOCK.lock().unwrap_or_else(|err| err.into_inner());
    apply(&app_settings_sync().map_err(to_napi_err)?).map_err(to_napi_err)
}

fn apply_update<T: serde::de::DeserializeOwned>(
    update: serde_json::Value,
    apply: impl FnOnce(&AppSettingsWithDiskSync, T) -> anyhow::Result<()>,
) -> napi::Result<()> {
    let update = serde_json::from_value(update)
        .map_err(anyhow::Error::from)
        .map_err(to_napi_err)?;
    locked_update(|settings| apply(settings, update))
}

/// Get the application settings.
#[napi(ts_return_type = "Promise<AppSettings>")]
pub async fn get_app_settings() -> napi::Result<serde_json::Value> {
    let settings = app_settings_sync().map_err(to_napi_err)?;
    settings
        .get()
        .and_then(|settings| Ok(serde_json::to_value(&*settings)?))
        .map_err(to_napi_err)
}

/// Set whether onboarding has been completed.
#[napi]
pub async fn update_onboarding_complete(update: bool) -> napi::Result<()> {
    locked_update(|settings| settings.update_onboarding_complete(update))
}

/// Set the telemetry distinct id; passing `null` or omitting the argument clears it.
#[napi]
pub async fn update_telemetry_distinct_id(app_distinct_id: Option<String>) -> napi::Result<()> {
    locked_update(|settings| settings.update_telemetry_distinct_id(app_distinct_id))
}

/// Update telemetry settings; unset fields are left unchanged.
#[napi]
pub async fn update_telemetry(
    #[napi(ts_arg_type = "TelemetryUpdate")] update: serde_json::Value,
) -> napi::Result<()> {
    apply_update(update, AppSettingsWithDiskSync::update_telemetry)
}

/// Update feature flags; unset fields are left unchanged.
#[napi]
pub async fn update_feature_flags(
    #[napi(ts_arg_type = "FeatureFlagsUpdate")] update: serde_json::Value,
) -> napi::Result<()> {
    apply_update(update, AppSettingsWithDiskSync::update_feature_flags)
}

/// Update review settings; unset fields are left unchanged.
#[napi]
pub async fn update_reviews(
    #[napi(ts_arg_type = "ReviewsUpdate")] update: serde_json::Value,
) -> napi::Result<()> {
    apply_update(update, AppSettingsWithDiskSync::update_reviews)
}

/// Update fetch settings; unset fields are left unchanged.
#[napi]
pub async fn update_fetch(
    #[napi(ts_arg_type = "FetchUpdate")] update: serde_json::Value,
) -> napi::Result<()> {
    apply_update(update, AppSettingsWithDiskSync::update_fetch)
}

/// Update UI settings; unset fields are left unchanged.
#[napi]
pub async fn update_ui(
    #[napi(ts_arg_type = "UiUpdate")] update: serde_json::Value,
) -> napi::Result<()> {
    apply_update(update, AppSettingsWithDiskSync::update_ui)
}
