#!/bin/bash

set -eu -o pipefail

git rev-parse --show-toplevel
git_root="$(git rev-parse --show-toplevel 2>/dev/null)"
cd "$git_root"

CRATE_ARGS="$(git grep "export-ts" | awk -F: '{ split($1, parts, "/"); if (length(parts) >= 3) { if (parts[1] == "crates") { crate = parts[2] } else { next } if (!seen[crate]++) print "-p " crate } }')"

# NOTE: export_bindings is generated by the TS proc-macro, and doesn't actually exist.
TS_RS_EXPORT_DIR="$PWD/packages/core/src/generated" cargo test ${CRATE_ARGS} --features export-ts export_bindings
pnpm format

if ! git diff --quiet; then
  git status
  echo "There are changed TS bindings. This error will go away with `git add .`, and on CI when the changes are committed."
  exit 2
fi