mod config;
mod ensure;
mod install;
mod script_behavior;
mod uninstall;

use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use anyhow::Result;
use but_hooks::managed_hooks::install_managed_hooks;
use tempfile::TempDir;

/// Helper to create a test hooks directory (simulates `.git/hooks/`)
fn create_hooks_dir() -> Result<(TempDir, PathBuf)> {
    crate::common::create_hooks_dir()
}

/// Helper to create a gix repo with its hooks directory for `ensure_managed_hooks` tests.
fn create_repo_with_hooks_dir() -> Result<(TempDir, gix::Repository, PathBuf)> {
    let temp_dir = TempDir::new()?;
    let repo = gix::init(temp_dir.path())?;
    let hooks_dir = repo.git_dir().join("hooks");
    fs::create_dir_all(&hooks_dir)?;
    Ok((temp_dir, repo, hooks_dir))
}

/// Helper to create a user hook file with content
fn create_user_hook(hooks_dir: &Path, hook_name: &str, content: &str) -> Result<()> {
    fs::create_dir_all(hooks_dir)?;
    let hook_path = hooks_dir.join(hook_name);
    fs::write(&hook_path, content)?;

    #[cfg(unix)]
    fs::set_permissions(&hook_path, fs::Permissions::from_mode(0o755))?;

    Ok(())
}

/// Helper to check if a file exists
fn hook_exists(hooks_dir: &Path, hook_name: &str) -> bool {
    hooks_dir.join(hook_name).exists()
}

/// Helper to read hook content
fn read_hook(hooks_dir: &Path, hook_name: &str) -> Result<String> {
    let path = hooks_dir.join(hook_name);
    Ok(fs::read_to_string(path)?)
}

/// Helper to create a GitButler-managed hook file directly (simulates prior installation)
fn create_managed_hook(hooks_dir: &Path, hook_name: &str) -> Result<()> {
    let content = format!(
        "#!/bin/sh\n# GITBUTLER_MANAGED_HOOK_V1\n# Test managed hook for {hook_name}\nexit 0\n"
    );
    create_user_hook(hooks_dir, hook_name, &content)
}

/// Helper to check if hook is executable on Unix
#[cfg(unix)]
fn is_executable(hooks_dir: &Path, hook_name: &str) -> bool {
    let path = hooks_dir.join(hook_name);
    if let Ok(metadata) = fs::metadata(&path) {
        let permissions = metadata.permissions();
        permissions.mode() & 0o111 != 0
    } else {
        false
    }
}

/// Assert that all three managed hook files exist in the given directory.
fn assert_all_hooks_exist(hooks_dir: &Path) {
    for name in ["pre-commit", "post-checkout", "pre-push"] {
        assert!(hook_exists(hooks_dir, name), "{name} should exist");
    }
}

/// Assert that none of the three managed hook files exist in the given directory.
fn assert_no_hooks_exist(hooks_dir: &Path) {
    for name in ["pre-commit", "post-checkout", "pre-push"] {
        assert!(!hook_exists(hooks_dir, name), "{name} should not exist");
    }
}

/// Assert that all three managed hook files contain the GitButler signature.
fn assert_all_hooks_have_signature(hooks_dir: &Path) {
    for name in ["pre-commit", "post-checkout", "pre-push"] {
        let content = read_hook(hooks_dir, name).unwrap();
        assert!(
            content.contains("GITBUTLER_MANAGED_HOOK_V1"),
            "{name} should have GitButler signature"
        );
    }
}

/// Assert that all three managed hook files are executable (Unix only).
#[cfg(unix)]
fn assert_all_hooks_executable(hooks_dir: &Path) {
    for name in ["pre-commit", "post-checkout", "pre-push"] {
        assert!(
            is_executable(hooks_dir, name),
            "{name} should be executable"
        );
    }
}

/// Create a hooks dir and install managed hooks in one step.
fn create_hooks_dir_with_managed_hooks() -> Result<(TempDir, PathBuf)> {
    let (temp, hooks_dir) = create_hooks_dir()?;
    install_managed_hooks(&hooks_dir, false, SystemTime::now())?;
    Ok((temp, hooks_dir))
}

/// Set up a prek-managed hook and `prek.toml` config file.
fn create_prek_environment(hooks_dir: &Path, workdir: &Path) -> Result<()> {
    let prek_hook = "#!/bin/sh\n# File generated by prek\nexec prek hook-impl pre-commit\n";
    create_user_hook(hooks_dir, "pre-commit", prek_hook)?;
    fs::write(workdir.join("prek.toml"), "# prek config\n")?;
    Ok(())
}
