use but_hooks::hook_manager::detect_hook_manager_in_hooks_dir;

use super::{create_hooks_dir, create_prek_config, with_binary_available};

const PREK: &str = "prek";

// ── Content-based detection ────────────────────────────────────────────────

#[test]
fn finds_prek_by_content() {
    let (dir, hooks_dir) = create_hooks_dir();

    let prek_hook = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
    std::fs::write(hooks_dir.join("pre-commit"), prek_hook).unwrap();

    let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
    assert!(result.is_some());
    let (name, instructions) = result.unwrap();
    assert_eq!(name, "prek");
    assert!(instructions.contains("but hook pre-commit"));
}

#[test]
fn returns_none_for_plain_hooks() {
    let (dir, hooks_dir) = create_hooks_dir();

    let plain_hook = "#!/bin/sh\necho 'my hook'\n";
    std::fs::write(hooks_dir.join("pre-commit"), plain_hook).unwrap();

    let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
    assert!(result.is_none());
}

#[test]
fn gitbutler_managed_hooks_not_detected_as_external() {
    let (dir, hooks_dir) = create_hooks_dir();

    // GitButler's own managed hook should NOT trigger external manager detection
    let gb_hook = "#!/bin/sh\n# GITBUTLER_MANAGED_HOOK_V1\necho 'workspace guard'\n";
    std::fs::write(hooks_dir.join("pre-commit"), gb_hook).unwrap();

    let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
    assert!(result.is_none());
}

#[test]
fn partial_ownership_detects_on_first_match() {
    let (dir, hooks_dir) = create_hooks_dir();

    // prek owns pre-commit, but post-checkout is a plain user hook
    let prek_hook = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
    std::fs::write(hooks_dir.join("pre-commit"), prek_hook).unwrap();
    std::fs::write(
        hooks_dir.join("post-checkout"),
        "#!/bin/sh\necho 'user hook'\n",
    )
    .unwrap();

    let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
    assert!(result.is_some(), "prek on any hook should be detected");
    assert_eq!(result.unwrap().0, "prek");
}

// ── Config-only fallback (no hook files present yet) ──────────────────────

// Config+binary fallback and project-local binary detection (.venv/bin,
// node_modules/.bin) are exercised by `detect_hook_manager` tests since
// both functions share `first_manager_with_config_and_binary`. Here we
// keep one representative positive test to verify the directory-level
// wiring, plus the unique negative case where existing hook files
// suppress the fallback.

#[test]
fn config_only_fallback_with_binary_available() {
    let (dir, hooks_dir) = create_hooks_dir();

    create_prek_config(dir.path());

    with_binary_available(PREK, || {
        let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
        assert!(result.is_some());
        let (name, _) = result.unwrap();
        assert_eq!(name, "prek");
    });
}

#[test]
fn ignores_config_fallback_when_plain_hook_exists() {
    let (dir, hooks_dir) = create_hooks_dir();

    create_prek_config(dir.path());
    std::fs::write(
        hooks_dir.join("pre-commit"),
        "#!/bin/sh\necho 'plain hook'\n",
    )
    .unwrap();

    // Config fallback should NOT apply when hook files exist (even with binary available)
    with_binary_available(PREK, || {
        let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
        assert!(result.is_none());
    });
}
