use but_hooks::hook_manager::{KnownManager, detect_hook_manager};
use tempfile::TempDir;

use super::{create_prek_config, with_binary_available, with_binary_unavailable};

const PREK: &str = "prek";

// ── Content-based detection (strong signal) ────────────────────────────────

#[test]
fn by_generated_comment() {
    let dir = TempDir::new().unwrap();
    let content = r#"#!/bin/sh
# File generated by prek: https://github.com/j178/prek
# ID: 182c10f181da4464a3eec51b83331688

HERE="$(cd "$(dirname "$0")" && pwd)"
PREK="/opt/homebrew/bin/prek"

if [ ! -x "$PREK" ]; then
    PREK="prek"
fi

exec "$PREK" hook-impl --hook-dir "$HERE" --script-version 4 --hook-type=pre-commit -- "$@"
"#;
    let result = detect_hook_manager(content, dir.path());
    assert_eq!(result, Some(KnownManager::Prek));
}

#[test]
fn by_hook_impl_invocation() {
    let dir = TempDir::new().unwrap();
    let content = "#!/bin/sh\nexec prek hook-impl --hook-type=pre-commit -- \"$@\"\n";
    let result = detect_hook_manager(content, dir.path());
    assert_eq!(result, Some(KnownManager::Prek));
}

#[test]
fn content_detection_does_not_require_binary_in_path() {
    let dir = TempDir::new().unwrap();
    let content = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
    // Binary NOT available, but content match should still detect
    with_binary_unavailable(PREK, || {
        let result = detect_hook_manager(content, dir.path());
        assert_eq!(result, Some(KnownManager::Prek));
    });
}

// ── Config-based detection (requires binary availability) ──────────────────

#[test]
fn by_config_file_when_binary_available() {
    let dir = TempDir::new().unwrap();
    create_prek_config(dir.path());
    with_binary_available(PREK, || {
        // Empty content = no hook file exists, config+binary fallback should fire
        let result = detect_hook_manager("", dir.path());
        assert_eq!(result, Some(KnownManager::Prek));
    });
}

#[test]
fn config_only_does_not_detect_when_binary_unavailable() {
    let dir = TempDir::new().unwrap();
    create_prek_config(dir.path());
    with_binary_unavailable(PREK, || {
        // Empty content = no hook file, but binary unavailable → no detection
        let result = detect_hook_manager("", dir.path());
        assert!(
            result.is_none(),
            "stale config should not trigger detection"
        );
    });
}

// ── No detection ───────────────────────────────────────────────────────────

#[test]
fn no_detection_for_plain_user_hook() {
    let dir = TempDir::new().unwrap();
    let content = "#!/bin/sh\necho 'my custom hook'\nexit 0\n";
    let result = detect_hook_manager(content, dir.path());
    assert!(result.is_none());
}

/// Plain user hook content must NOT trigger config+binary fallback even when
/// prek.toml exists and the binary is available. The content-based check
/// already determined the hook is user-owned — config fallback should only
/// apply when there is no content to inspect (empty string).
#[test]
fn no_detection_for_plain_user_hook_with_config_and_binary() {
    let dir = TempDir::new().unwrap();
    create_prek_config(dir.path());
    let content = "#!/bin/sh\necho 'my custom hook'\nexit 0\n";
    with_binary_available(PREK, || {
        let result = detect_hook_manager(content, dir.path());
        assert!(
            result.is_none(),
            "plain user hook should not be detected as prek-managed \
             even when prek.toml exists and binary is available"
        );
    });
}

#[test]
fn no_detection_without_config_or_content() {
    let dir = TempDir::new().unwrap();
    let result = detect_hook_manager("", dir.path());
    assert!(result.is_none());
}

// ── Priority: content wins over config ────────────────────────────────────

#[test]
fn content_match_wins_regardless_of_binary_availability() {
    let dir = TempDir::new().unwrap();
    create_prek_config(dir.path());
    let prek_content = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
    // Even with binary unavailable, content signature is enough
    with_binary_unavailable(PREK, || {
        let result = detect_hook_manager(prek_content, dir.path());
        assert_eq!(result, Some(KnownManager::Prek));
    });
}

// ── Project-local binary detection (.venv/bin, node_modules/.bin) ─────────

#[test]
fn by_config_file_when_binary_in_venv() {
    let dir = TempDir::new().unwrap();
    create_prek_config(dir.path());

    // Simulate `uv add --dev prek` by creating .venv/bin/prek
    let venv_bin = dir.path().join(".venv/bin");
    std::fs::create_dir_all(&venv_bin).unwrap();
    std::fs::write(venv_bin.join("prek"), "#!/bin/sh\n# mock prek binary").unwrap();

    // Binary not on system PATH, but exists in .venv/bin/
    with_binary_unavailable(PREK, || {
        // Empty content = no hook file, config+binary fallback should fire
        let result = detect_hook_manager("", dir.path());
        assert_eq!(
            result,
            Some(KnownManager::Prek),
            "should detect prek via .venv/bin/ when not on system PATH"
        );
    });
}

#[test]
fn by_config_file_when_binary_in_node_modules() {
    let dir = TempDir::new().unwrap();
    create_prek_config(dir.path());

    // Simulate `npm add -D @j178/prek` by creating node_modules/.bin/prek
    let nm_bin = dir.path().join("node_modules/.bin");
    std::fs::create_dir_all(&nm_bin).unwrap();
    std::fs::write(nm_bin.join("prek"), "#!/bin/sh\n# mock prek binary").unwrap();

    // Binary not on system PATH, but exists in node_modules/.bin/
    with_binary_unavailable(PREK, || {
        // Empty content = no hook file, config+binary fallback should fire
        let result = detect_hook_manager("", dir.path());
        assert_eq!(
            result,
            Some(KnownManager::Prek),
            "should detect prek via node_modules/.bin/ when not on system PATH"
        );
    });
}

#[test]
fn no_detection_when_binary_missing_from_all_locations() {
    let dir = TempDir::new().unwrap();
    create_prek_config(dir.path());
    // No .venv/bin/prek, no node_modules/.bin/prek, not on PATH
    with_binary_unavailable(PREK, || {
        // Empty content = no hook file, config exists but no binary anywhere
        let result = detect_hook_manager("", dir.path());
        assert!(
            result.is_none(),
            "config-only without any binary should not trigger detection"
        );
    });
}
