//! End-to-end integration tests for prek ↔ GitButler hook coexistence.
//!
//! These tests exercise real `prek install` against a Sandbox repo to verify
//! that `but setup` correctly detects prek-managed hooks, `--force-hooks`
//! overrides them, and diagnostic output is accurate.
//!
//! Lower-level detection logic (content matching, config+binary fallback,
//! project-local binaries) is covered by `but-hooks` crate tests. `but hook`
//! subcommand behavior is covered by `hook.rs`. This file focuses on the
//! unique value of running against a **real prek binary**.
//!
//! All tests are `#[ignore]` because they require the `prek` binary on PATH.
//! Run them explicitly with:
//!
//! ```sh
//! cargo test -p but -- --ignored hook_prek
//! ```

use crate::utils::{CommandExt as _, Sandbox};

/// Realistic prek.toml without GitButler entries — tests detection + instruction printing.
const PREK_TOML_REALISTIC: &str = r#"
default_install_hook_types = ["pre-commit", "post-checkout", "pre-push"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace", stages = ["pre-commit"], priority = 0 },
  { id = "end-of-file-fixer", stages = ["pre-commit"], priority = 0 },
  { id = "check-toml", stages = ["pre-commit"], priority = 0 },
]

[[repos]]
repo = "local"
hooks = [
  { id = "no-commit-to-main",
    name = "Block commits to main",
    language = "system",
    entry = "bash -c 'test \"$(git symbolic-ref --short HEAD 2>/dev/null)\" != main'",
    pass_filenames = false,
    always_run = true,
    stages = ["pre-commit"],
    priority = 100 },
]
"#;

/// Minimal builtin-only prek.toml — fast, no-network fallback for speed-sensitive tests.
const PREK_TOML_MINIMAL: &str = r#"
[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace", priority = 0 },
  { id = "end-of-file-fixer", priority = 0 },
  { id = "check-toml", priority = 0 },
]
"#;

/// Write `prek.toml` and run `prek install` in the sandbox's project root.
fn install_prek(env: &Sandbox, config: &str) {
    env.file("prek.toml", config);
    env.invoke_bash("prek install --install-hooks");
}

// ── Core detection with real prek hooks ─────────────────────────────

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn setup_detects_real_prek_hooks() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    install_prek(&env, PREK_TOML_REALISTIC);

    // Verify prek actually installed hooks with its signature
    let hook_content = std::fs::read_to_string(env.projects_root().join(".git/hooks/pre-commit"))?;
    assert!(
        hook_content.contains("File generated by prek") || hook_content.contains("prek hook-impl"),
        "prek should have installed a hook with its signature, got: {hook_content}"
    );

    // `but setup` should detect prek and print integration instructions
    env.but("setup")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Detected prek managing your git hooks.
  GitButler will not overwrite hooks owned by your hook manager.
...
"#]]);

    // Verify ALL prek hooks were NOT overwritten
    for hook_name in ["pre-commit", "post-checkout", "pre-push"] {
        let hook_after =
            std::fs::read_to_string(env.projects_root().join(format!(".git/hooks/{hook_name}")))?;
        assert!(
            hook_after.contains("File generated by prek") || hook_after.contains("prek hook-impl"),
            "{hook_name} hook should be preserved after `but setup`, got: {hook_after}"
        );
    }

    Ok(())
}

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn force_hooks_overrides_real_prek() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    install_prek(&env, PREK_TOML_MINIMAL);

    env.but("setup --force-hooks")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Forcing hook installation (--force-hooks), skipping detection.
...
"#]]);

    // Verify GitButler hooks replaced prek hooks
    let hook_content = std::fs::read_to_string(env.projects_root().join(".git/hooks/pre-commit"))?;
    assert!(
        hook_content.contains("GITBUTLER_MANAGED_HOOK_V1"),
        "GitButler hook should replace prek hook after --force-hooks"
    );

    // Verify prek hook was backed up
    let backup_path = env.projects_root().join(".git/hooks/pre-commit-user");
    assert!(
        backup_path.exists(),
        "original prek hook should be backed up to pre-commit-user"
    );

    Ok(())
}

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn json_output_detects_real_prek() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    install_prek(&env, PREK_TOML_MINIMAL);

    env.but("--json setup")
        .allow_json()
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
{
  "repositoryPath": "[..]",
  "projectStatus": "[..]",
  "target": {
    "branchName": "[..]",
    "remoteName": "[..]",
    "newlySet": true
  },
  "hookManager": {
    "name": "prek",
    "hooksInstalled": false
  },
  "hooks": []
}

"#]]);

    Ok(())
}

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn hook_status_shows_prek_as_external() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    install_prek(&env, PREK_TOML_REALISTIC);
    env.but("setup").assert().success();

    env.but("hook status")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Hook manager:        prek
...
  pre-commit:          ● external (prek)
...
"#]]);

    Ok(())
}

// ── Lifecycle: force-install ↔ prek reinstall ──────────────────────

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn force_install_then_prek_reinstall_recovers() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    // Step 1: prek owns the hooks
    install_prek(&env, PREK_TOML_MINIMAL);

    // Step 2: --force-hooks overwrites prek with GitButler hooks
    env.but("setup --force-hooks").assert().success();
    let content = std::fs::read_to_string(env.projects_root().join(".git/hooks/pre-commit"))?;
    assert!(content.contains("GITBUTLER_MANAGED_HOOK_V1"));

    // Step 3: prek reclaims the hooks (real-world: user runs `prek install`)
    env.invoke_bash("prek install --install-hooks");
    let content = std::fs::read_to_string(env.projects_root().join(".git/hooks/pre-commit"))?;
    assert!(
        content.contains("File generated by prek") || content.contains("prek hook-impl"),
        "prek should reclaim hooks after reinstall"
    );

    // Step 4: `but setup` re-detects prek
    env.but("setup")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Detected prek managing your git hooks.
...
"#]]);

    Ok(())
}

// ── Subsequent setup runs after prek detection ──────────────────────

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn setup_rerun_after_prek_detection_shows_prek_message() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    install_prek(&env, PREK_TOML_MINIMAL);

    // First run: detects prek, persists installHooks=false
    env.but("setup")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Detected prek managing your git hooks.
...
"#]]);

    assert_eq!(
        env.invoke_git("config --local --get gitbutler.installHooks"),
        "false",
        "installHooks should be persisted as false after first prek detection"
    );

    // Second run: installHooks=false is already set, but prek hooks are still present.
    // Should re-detect prek and show the informative message, not the generic
    // "--no-hooks is configured" fallback.
    env.but("setup")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Detected prek managing your git hooks.
...
"#]]);

    Ok(())
}

// ── Config-only fallback (prek.toml exists, hooks not installed) ────

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn config_only_detection_when_prek_on_path() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    // Write prek.toml but do NOT run `prek install`
    env.file("prek.toml", PREK_TOML_REALISTIC);

    // prek binary is on PATH + config exists → config-only fallback should detect
    env.but("setup")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Detected prek managing your git hooks.
...
"#]]);

    Ok(())
}

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn prek_uninstall_leaves_config_only_detection() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    // Install prek, then uninstall — hook files are gone but prek.toml remains
    install_prek(&env, PREK_TOML_MINIMAL);
    env.invoke_bash("prek uninstall");

    assert!(
        !env.projects_root().join(".git/hooks/pre-commit").exists(),
        "prek uninstall should remove hook files"
    );

    // prek.toml + binary on PATH → config-only fallback should still detect
    env.but("setup")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Detected prek managing your git hooks.
...
"#]]);

    Ok(())
}

#[test]
#[ignore = "requires prek binary — run with: cargo test -p but -- --ignored hook_prek"]
fn project_local_prek_binary_detected_via_venv() -> anyhow::Result<()> {
    let env = Sandbox::open_with_default_settings("repo-no-remote")?;

    // prek.toml exists but no hooks installed, binary only in .venv/bin/
    env.file("prek.toml", PREK_TOML_REALISTIC);
    env.invoke_bash("mkdir -p .venv/bin && cp $(which prek) .venv/bin/prek");

    // `but setup` should detect via config + .venv/bin/ project-local binary
    env.but("setup")
        .assert()
        .success()
        .stdout_eq(snapbox::str![[r#"
...
  Detected prek managing your git hooks.
...
"#]]);

    Ok(())
}
