//! Detection and integration with external Git hook managers.
//!
//! When GitButler sets up a project (`but setup`), it may encounter hooks owned by
//! external hook managers. This module provides detection for these managers and
//! generates integration instructions instead of silently displacing their hooks.
//!
//! Currently only **prek** is supported. The architecture is modular — adding a
//! new manager requires:
//! 1. Add a variant to [`KnownManager`]
//! 2. Implement `owns_hook()`, `has_config()`, `is_available()`, and
//!    `integration_instructions()` match arms
//! 3. Add the variant to `ALL_MANAGERS`
//! 4. Add tests
//!
//! The detection logic lives here alongside `managed_hooks` because both the
//! CLI (`setup.rs`) and the desktop app (`integration.rs`) need to check for
//! hook managers before deciding whether to install managed hooks.

use std::path::Path;

/// A recognized external hook manager that may own git hook files.
///
/// Variants are listed in priority order (checked first to last via `ALL_MANAGERS`).
/// Currently only prek is supported — see the module-level docs for how to add more.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KnownManager {
    /// prek — a fast, Rust-based alternative to pre-commit.
    /// See: <https://prek.j178.dev/>
    Prek,
}

/// All known hook managers in priority order.
///
/// Detection iterates this list — the first match wins. Add new managers here
/// after implementing the required [`KnownManager`] match arms.
const ALL_MANAGERS: &[KnownManager] = &[KnownManager::Prek];

impl KnownManager {
    /// Human-readable name of the hook manager.
    pub fn name(self) -> &'static str {
        match self {
            Self::Prek => "prek",
        }
    }

    /// Check if the given hook file content was generated by this manager.
    pub fn owns_hook(self, content: &str) -> bool {
        match self {
            Self::Prek => {
                content.contains("# File generated by prek") || content.contains("prek hook-impl")
            }
        }
    }

    /// Check if configuration files for this manager exist in the repository working directory.
    pub fn has_config(self, workdir: &Path) -> bool {
        match self {
            Self::Prek => workdir.join("prek.toml").exists(),
        }
    }

    /// Check if the manager's binary is available on the system PATH or in
    /// common project-local locations.
    ///
    /// Used as an additional gate for config-only detection: when a config file
    /// exists but no hook files are present, we only consider the manager active
    /// if its binary is reachable. This prevents false positives from stale or
    /// committed config files when the manager is not actually installed.
    ///
    /// Checks (in order):
    /// 1. System PATH (covers `brew install prek`, `cargo binstall prek`, etc.)
    /// 2. `.venv/bin/` (covers `uv add --dev prek`, `pip install prek`)
    /// 3. `node_modules/.bin/` (covers `npm add -D @j178/prek`, `pnpm add -D @j178/prek`)
    pub fn is_available(self, workdir: &Path) -> bool {
        let binary = match self {
            Self::Prek => "prek",
        };
        if is_binary_in_path(binary) {
            return true;
        }
        // Check common project-local locations for the binary.
        // Python venvs use `Scripts` on Windows and `bin` on Unix.
        let venv_bin = if cfg!(windows) {
            ".venv/Scripts"
        } else {
            ".venv/bin"
        };
        let local_paths = [
            workdir.join(venv_bin).join(binary),
            workdir.join("node_modules/.bin").join(binary),
        ];
        if local_paths.iter().any(|p| p.exists()) {
            return true;
        }
        // On Windows, binaries may have `.exe` or `.cmd` extensions that `Path::exists()`
        // won't match without them — unlike `which::which` which handles this automatically.
        // npm creates `.cmd` wrappers in `node_modules/.bin`; Python venvs use `.exe`.
        #[cfg(windows)]
        {
            let win_extensions = ["exe", "cmd"];
            if local_paths.iter().any(|p| {
                win_extensions
                    .iter()
                    .any(|ext| p.with_extension(ext).exists())
            }) {
                return true;
            }
        }
        false
    }

    /// Generate user-facing integration instructions explaining how to add
    /// GitButler's workspace guard to their hook manager configuration.
    pub fn integration_instructions(self) -> &'static str {
        match self {
            Self::Prek => {
                r#"1. Ensure post-checkout is in default_install_hook_types in your prek.toml
   (prek won't install the hook script without it):

     default_install_hook_types = ["pre-commit", "pre-push", "post-checkout"]

2. Add the following [[repos]] entry to your prek.toml:

     [[repos]]
     repo = "local"
     hooks = [
         { id = "gitbutler-workspace-guard",
           name = "GitButler Workspace Guard",
           language = "system",
           entry = "but hook pre-commit",
           pass_filenames = false,
           always_run = true,
           stages = ["pre-commit"] },
         { id = "gitbutler-post-checkout",
           name = "GitButler Post-Checkout Cleanup",
           language = "system",
           entry = "but hook post-checkout",
           pass_filenames = false,
           always_run = true,
           stages = ["post-checkout"] },
         { id = "gitbutler-push-guard",
           name = "GitButler Push Guard",
           language = "system",
           entry = "but hook pre-push",
           pass_filenames = false,
           always_run = true,
           stages = ["pre-push"] },
     ]

3. Run: prek install"#
            }
        }
    }
}

/// Return the first manager from `ALL_MANAGERS` that has both a config file
/// and an available binary in `workdir`, or `None` if no such manager exists.
///
/// This predicate is used in two places: once by [`detect_hook_manager`] (when
/// the hook content is empty) and once by [`detect_hook_manager_in_hooks_dir`]
/// (when no hook files exist yet). Centralising it here avoids having the
/// same iterator expression duplicated across both call sites.
fn first_manager_with_config_and_binary(workdir: &Path) -> Option<KnownManager> {
    ALL_MANAGERS
        .iter()
        .find(|m| m.has_config(workdir) && m.is_available(workdir))
        .copied()
}

/// Check if a binary is available on the system PATH.
///
/// This is a lightweight check used by [`KnownManager::is_available`] to
/// verify that a hook manager's binary is actually installed, not just
/// configured.
///
/// When the `test-overrides` feature is enabled, the env var
/// `_GITBUTLER_TEST_BINARY_{NAME}_AVAILABLE` (where `{NAME}` is the uppercased
/// binary name, e.g. `_GITBUTLER_TEST_BINARY_PREK_AVAILABLE`) overrides the
/// real `which::which` check for that specific binary:
/// - `"1"` → return true  (simulate binary present)
/// - `"0"` → return false (simulate binary absent)
/// - unset → real `which::which` check
///
/// Using a per-binary variable ensures parallel tests for different managers
/// cannot interfere with each other. Use the `with_binary_available` /
/// `with_binary_unavailable` helpers (via `temp_env`) to control this in a
/// thread-safe manner.
///
/// The `test-overrides` feature must not be enabled in production builds.
fn is_binary_in_path(binary: &str) -> bool {
    #[cfg(feature = "test-overrides")]
    {
        let env_key = format!("_GITBUTLER_TEST_BINARY_{}_AVAILABLE", binary.to_uppercase());
        if let Ok(val) = std::env::var(&env_key) {
            return val == "1";
        }
    }
    which::which(binary).is_ok()
}

/// Detect which hook manager (if any) owns the given hook file content.
///
/// Checks each known manager in priority order:
/// 1. **Content signature** (strong) — hook content matches a manager's fingerprint
/// 2. **Config + binary** (medium) — config files exist and manager binary is in PATH
///
/// If only a config file exists but the binary is not available, returns `None`
/// to avoid false positives from stale or committed config files.
///
/// Returns `None` if no known hook manager is detected.
pub fn detect_hook_manager(hook_content: &str, workdir: &Path) -> Option<KnownManager> {
    // First pass: check hook content signatures (most reliable)
    if let Some(&manager) = ALL_MANAGERS.iter().find(|m| m.owns_hook(hook_content)) {
        return Some(manager);
    }

    // Config+binary fallback: only when there is no hook content to inspect.
    // If non-empty content was provided but didn't match any manager signature,
    // the hook is user-owned — config presence is irrelevant.
    if hook_content.is_empty()
        && let Some(manager) = first_manager_with_config_and_binary(workdir)
    {
        return Some(manager);
    }

    None
}

/// Names of hooks that GitButler manages via shell scripts in `.git/hooks/`.
///
/// Used by `but setup` to check whether any of these hooks are owned by an
/// external hook manager before deciding to install managed hooks.
///
pub const MANAGED_HOOK_NAMES: &[&str] = &["pre-commit", "post-checkout", "pre-push"];

/// Build the shell `rm` command string that removes all managed hook files
/// from the default `.git/hooks/` directory.
///
/// Callers should prefer this over hand-rolling the hook name list so that
/// the list stays in sync with [`MANAGED_HOOK_NAMES`] automatically.
pub fn orphaned_hooks_remove_command() -> String {
    let paths: Vec<String> = MANAGED_HOOK_NAMES
        .iter()
        .map(|name| format!(".git/hooks/{name}"))
        .collect();
    format!("rm {}", paths.join(" "))
}

/// Check all managed hook files for external hook manager ownership.
///
/// Reads each hook file in `hooks_dir` and checks whether any known hook
/// manager owns it. If a manager is detected on **any** hook, returns
/// `Some((manager_name, instructions))`. This implements all-or-nothing
/// semantics: if a hook manager is detected, GitButler should not install
/// any managed hooks — the user should wire everything through their
/// hook manager using the returned instructions.
///
/// Returns `None` if no known hook manager is detected on any hook.
pub fn detect_hook_manager_in_hooks_dir(
    hooks_dir: &Path,
    workdir: &Path,
) -> Option<(&'static str, &'static str)> {
    let mut saw_hook_file = false;

    for hook_name in MANAGED_HOOK_NAMES {
        let hook_path = hooks_dir.join(hook_name);
        if hook_path.exists() {
            saw_hook_file = true;
            match std::fs::read_to_string(&hook_path) {
                Ok(content) => {
                    if let Some(&manager) = ALL_MANAGERS.iter().find(|m| m.owns_hook(&content)) {
                        tracing::info!(
                            "Detected {} managing {} hook, skipping all hook installations",
                            manager.name(),
                            hook_name
                        );
                        return Some((manager.name(), manager.integration_instructions()));
                    }
                }
                Err(e) => {
                    tracing::debug!(
                        path = %hook_path.display(),
                        error = %e,
                        "Could not read hook file during manager detection; skipping"
                    );
                }
            }
        }
    }

    // Fallback: check config files + binary availability when no hook files exist yet.
    // This catches hook managers that are configured (e.g. prek.toml exists) and
    // available on PATH, but haven't installed their hooks yet (e.g. `prek install`
    // not yet run). The binary check prevents false positives from stale config files.
    if !saw_hook_file && let Some(manager) = first_manager_with_config_and_binary(workdir) {
        tracing::info!(
            "Detected {} config in workdir with binary available (no hook files yet), \
             skipping hook installations",
            manager.name()
        );
        return Some((manager.name(), manager.integration_instructions()));
    }

    // If a config file exists but the binary is not available, log it but proceed
    // with managed mode — the manager is configured but inactive.
    if !saw_hook_file && let Some(&manager) = ALL_MANAGERS.iter().find(|m| m.has_config(workdir)) {
        tracing::info!(
            "Found {} config in workdir but binary is not available, \
             proceeding with GitButler managed hooks",
            manager.name()
        );
    }

    None
}
