[package]
name = "but-lisp"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
miette.workspace = true
thiserror.workspace = true
bstr.workspace = true
globset = "0.4.18"

[dev-dependencies]
snapbox.workspace = true

[lints]
workspace = true
