/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProjectIdRouteRouteImport } from "./routes/project/$id/route"
import { Route as ProjectIdWorkspaceRouteRouteImport } from "./routes/project/$id/workspace/route"
import { Route as ProjectIdBranchesRouteRouteImport } from "./routes/project/$id/branches/route"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRouteRoute = ProjectIdRouteRouteImport.update({
  id: "/project/$id",
  path: "/project/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdWorkspaceRouteRoute = ProjectIdWorkspaceRouteRouteImport.update({
  id: "/workspace",
  path: "/workspace",
  getParentRoute: () => ProjectIdRouteRoute,
} as any)
const ProjectIdBranchesRouteRoute = ProjectIdBranchesRouteRouteImport.update({
  id: "/branches",
  path: "/branches",
  getParentRoute: () => ProjectIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/project/$id": typeof ProjectIdRouteRouteWithChildren
  "/project/$id/branches": typeof ProjectIdBranchesRouteRoute
  "/project/$id/workspace": typeof ProjectIdWorkspaceRouteRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/project/$id": typeof ProjectIdRouteRouteWithChildren
  "/project/$id/branches": typeof ProjectIdBranchesRouteRoute
  "/project/$id/workspace": typeof ProjectIdWorkspaceRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/project/$id": typeof ProjectIdRouteRouteWithChildren
  "/project/$id/branches": typeof ProjectIdBranchesRouteRoute
  "/project/$id/workspace": typeof ProjectIdWorkspaceRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/project/$id"
    | "/project/$id/branches"
    | "/project/$id/workspace"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/project/$id" | "/project/$id/branches" | "/project/$id/workspace"
  id:
    | "__root__"
    | "/"
    | "/project/$id"
    | "/project/$id/branches"
    | "/project/$id/workspace"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRouteRoute: typeof ProjectIdRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/project/$id": {
      id: "/project/$id"
      path: "/project/$id"
      fullPath: "/project/$id"
      preLoaderRoute: typeof ProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/project/$id/workspace": {
      id: "/project/$id/workspace"
      path: "/workspace"
      fullPath: "/project/$id/workspace"
      preLoaderRoute: typeof ProjectIdWorkspaceRouteRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
    "/project/$id/branches": {
      id: "/project/$id/branches"
      path: "/branches"
      fullPath: "/project/$id/branches"
      preLoaderRoute: typeof ProjectIdBranchesRouteRouteImport
      parentRoute: typeof ProjectIdRouteRoute
    }
  }
}

interface ProjectIdRouteRouteChildren {
  ProjectIdBranchesRouteRoute: typeof ProjectIdBranchesRouteRoute
  ProjectIdWorkspaceRouteRoute: typeof ProjectIdWorkspaceRouteRoute
}

const ProjectIdRouteRouteChildren: ProjectIdRouteRouteChildren = {
  ProjectIdBranchesRouteRoute: ProjectIdBranchesRouteRoute,
  ProjectIdWorkspaceRouteRoute: ProjectIdWorkspaceRouteRoute,
}

const ProjectIdRouteRouteWithChildren = ProjectIdRouteRoute._addFileChildren(
  ProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRouteRoute: ProjectIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
