import type { Theme } from './theme';

const palette = {
    dark0Hard: '#1d2021',
    dark0: '#282828',
    dark0Soft: '#32302f',
    dark1: '#3c3836',
    dark2: '#504945',
    dark3: '#665c54',
    dark4: '#7c6f64',
    light0Hard: '#f9f5d7',
    light0: '#fbf1c7',
    light0Soft: '#f2e5bc',
    light1: '#ebdbb2',
    light2: '#d5c4a1',
    light3: '#bdae93',
    light4: '#a89984',
    brightRed: '#fb4934',
    brightGreen: '#b8bb26',
    brightYellow: '#fabd2f',
    brightBlue: '#83a598',
    brightPurple: '#d3869b',
    brightAqua: '#8ec07c',
    brightOrange: '#fe8019',
    neutralRed: '#cc241d',
    neutralGreen: '#98971a',
    neutralYellow: '#d79921',
    neutralBlue: '#458588',
    neutralPurple: '#b16286',
    neutralAqua: '#689d6a',
    neutralOrange: '#d65d0e',
    fadedRed: '#9d0006',
    fadedGreen: '#79740e',
    fadedYellow: '#b57614',
    fadedBlue: '#076678',
    fadedPurple: '#8f3f71',
    fadedAqua: '#427b58',
    fadedOrange: '#af3a03',
    gray: '#928374'
};

export const dark: Theme = {
    bg0: palette.dark0,
    bg1: palette.dark1,
    bg2: palette.dark2,
    bg3: palette.dark3,
    bg4: palette.dark4,
    fg0: palette.light0,
    fg1: palette.light1,
    fg2: palette.light2,
    fg3: palette.light3,
    fg4: palette.light4,
    red: palette.brightRed,
    green: palette.brightGreen,
    yellow: palette.brightYellow,
    blue: palette.brightBlue,
    purple: palette.brightPurple,
    aqua: palette.brightAqua,
    orange: palette.brightOrange,
    neutralRed: palette.neutralRed,
    neutralGreen: palette.neutralGreen,
    neutralYellow: palette.neutralYellow,
    neutralBlue: palette.neutralBlue,
    neutralPurple: palette.neutralPurple,
    neutralAqua: palette.neutralAqua,
    gray: palette.gray
};

export const light: Theme = {
    bg0: palette.light0,
    bg1: palette.light1,
    bg2: palette.light2,
    bg3: palette.light3,
    bg4: palette.light4,
    fg0: palette.dark0,
    fg1: palette.dark1,
    fg2: palette.dark2,
    fg3: palette.dark3,
    fg4: palette.dark4,
    red: palette.fadedRed,
    green: palette.fadedGreen,
    yellow: palette.fadedYellow,
    blue: palette.fadedBlue,
    purple: palette.fadedPurple,
    aqua: palette.fadedAqua,
    orange: palette.fadedOrange,
    neutralRed: palette.neutralRed,
    neutralGreen: palette.neutralGreen,
    neutralYellow: palette.neutralYellow,
    neutralBlue: palette.neutralBlue,
    neutralPurple: palette.neutralPurple,
    neutralAqua: palette.neutralAqua,
    gray: palette.gray
};
