//! Detection and integration with external Git hook managers.
//!
//! When GitButler sets up a project (`but setup`), it may encounter hooks owned by
//! external hook managers. This module provides detection for these managers and
//! generates integration instructions instead of silently displacing their hooks.
//!
//! Currently only **prek** is supported. The architecture is modular — adding a
//! new manager requires:
//! 1. Add a variant to [`KnownManager`]
//! 2. Implement `owns_hook()`, `has_config()`, `is_available()`, and
//!    `integration_instructions()` match arms
//! 3. Add the variant to `ALL_MANAGERS`
//! 4. Add tests
//!
//! The detection logic lives here alongside `managed_hooks` because both the
//! CLI (`setup.rs`) and the desktop app (`integration.rs`) need to check for
//! hook managers before deciding whether to install managed hooks.

use std::path::Path;

/// A recognized external hook manager that may own git hook files.
///
/// Variants are listed in priority order (checked first to last via `ALL_MANAGERS`).
/// Currently only prek is supported — see the module-level docs for how to add more.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KnownManager {
    /// prek — a fast, Rust-based alternative to pre-commit.
    /// See: <https://prek.j178.dev/>
    Prek,
}

/// All known hook managers in priority order.
///
/// Detection iterates this list — the first match wins. Add new managers here
/// after implementing the required [`KnownManager`] match arms.
const ALL_MANAGERS: &[KnownManager] = &[KnownManager::Prek];

impl KnownManager {
    /// Human-readable name of the hook manager.
    pub fn name(self) -> &'static str {
        match self {
            Self::Prek => "prek",
        }
    }

    /// Check if the given hook file content was generated by this manager.
    pub fn owns_hook(self, content: &str) -> bool {
        match self {
            Self::Prek => {
                content.contains("# File generated by prek") || content.contains("prek hook-impl")
            }
        }
    }

    /// Check if configuration files for this manager exist in the repository working directory.
    pub fn has_config(self, workdir: &Path) -> bool {
        match self {
            Self::Prek => workdir.join("prek.toml").exists(),
        }
    }

    /// Check if the manager's binary is available on the system PATH or in
    /// common project-local locations.
    ///
    /// Used as an additional gate for config-only detection: when a config file
    /// exists but no hook files are present, we only consider the manager active
    /// if its binary is reachable. This prevents false positives from stale or
    /// committed config files when the manager is not actually installed.
    ///
    /// Checks (in order):
    /// 1. System PATH (covers `brew install prek`, `cargo binstall prek`, etc.)
    /// 2. `.venv/bin/` (covers `uv add --dev prek`, `pip install prek`)
    /// 3. `node_modules/.bin/` (covers `npm add -D @j178/prek`, `pnpm add -D @j178/prek`)
    pub fn is_available(self, workdir: &Path) -> bool {
        let binary = match self {
            Self::Prek => "prek",
        };
        if is_binary_in_path(binary) {
            return true;
        }
        // Check common project-local locations for the binary.
        let local_paths = [
            workdir.join(".venv/bin").join(binary),
            workdir.join("node_modules/.bin").join(binary),
        ];
        local_paths.iter().any(|p| p.exists())
    }

    /// Generate user-facing integration instructions explaining how to add
    /// GitButler's workspace guard to their hook manager configuration.
    pub fn integration_instructions(self) -> &'static str {
        match self {
            Self::Prek => {
                r#"Add the following to your prek.toml to integrate GitButler's workspace guard:

  [[repos]]
  repo = "local"
  hooks = [
      { id = "gitbutler-workspace-guard",
        name = "GitButler Workspace Guard",
        language = "system",
        entry = "but hook pre-commit",
        pass_filenames = false,
        always_run = true,
        stages = ["pre-commit"] },
      { id = "gitbutler-post-checkout",
        name = "GitButler Post-Checkout Cleanup",
        language = "system",
        entry = "but hook post-checkout",
        pass_filenames = false,
        always_run = true,
        stages = ["post-checkout"] },
      { id = "gitbutler-push-guard",
        name = "GitButler Push Guard",
        language = "system",
        entry = "but hook pre-push",
        pass_filenames = false,
        always_run = true,
        stages = ["pre-push"] },
  ]"#
            }
        }
    }
}

/// Check if a binary is available on the system PATH.
///
/// This is a lightweight check used by [`KnownManager::is_available`] to
/// verify that a hook manager's binary is actually installed, not just
/// configured. In tests, the `#[cfg(test)]` override allows controlling
/// the result without requiring the real binary.
fn is_binary_in_path(binary: &str) -> bool {
    #[cfg(test)]
    {
        // In tests, we use an environment variable to control binary availability.
        // Set `_GITBUTLER_TEST_BINARY_AVAILABLE=1` to simulate the binary being present.
        let _ = binary;
        std::env::var("_GITBUTLER_TEST_BINARY_AVAILABLE").is_ok()
    }
    #[cfg(not(test))]
    {
        which::which(binary).is_ok()
    }
}

/// Detect which hook manager (if any) owns the given hook file content.
///
/// Checks each known manager in priority order:
/// 1. **Content signature** (strong) — hook content matches a manager's fingerprint
/// 2. **Config + binary** (medium) — config files exist and manager binary is in PATH
///
/// If only a config file exists but the binary is not available, returns `None`
/// to avoid false positives from stale or committed config files.
///
/// Returns `None` if no known hook manager is detected.
pub fn detect_hook_manager(hook_content: &str, workdir: &Path) -> Option<KnownManager> {
    // First pass: check hook content signatures (most reliable)
    if let Some(&manager) = ALL_MANAGERS.iter().find(|m| m.owns_hook(hook_content)) {
        return Some(manager);
    }

    // Second pass: check config file presence + binary availability (fallback)
    if let Some(&manager) = ALL_MANAGERS
        .iter()
        .find(|m| m.has_config(workdir) && m.is_available(workdir))
    {
        return Some(manager);
    }

    None
}

/// Names of hooks that GitButler manages via shell scripts in `.git/hooks/`.
///
/// Used by `but setup` to check whether any of these hooks are owned by an
/// external hook manager before deciding to install managed hooks.
///
pub const MANAGED_HOOK_NAMES: &[&str] = &["pre-commit", "post-checkout", "pre-push"];

/// Check all managed hook files for external hook manager ownership.
///
/// Reads each hook file in `hooks_dir` and checks whether any known hook
/// manager owns it. If a manager is detected on **any** hook, returns
/// `Some((manager_name, instructions))`. This implements all-or-nothing
/// semantics: if a hook manager is detected, GitButler should not install
/// any managed hooks — the user should wire everything through their
/// hook manager using the returned instructions.
///
/// Returns `None` if no known hook manager is detected on any hook.
pub fn detect_hook_manager_in_hooks_dir(
    hooks_dir: &Path,
    workdir: &Path,
) -> Option<(&'static str, &'static str)> {
    let mut saw_hook_file = false;

    for hook_name in MANAGED_HOOK_NAMES {
        let hook_path = hooks_dir.join(hook_name);
        if hook_path.exists() {
            saw_hook_file = true;
            if let Ok(content) = std::fs::read_to_string(&hook_path)
                && let Some(&manager) = ALL_MANAGERS.iter().find(|m| m.owns_hook(&content))
            {
                tracing::info!(
                    "Detected {} managing {} hook, skipping all hook installations",
                    manager.name(),
                    hook_name
                );
                return Some((manager.name(), manager.integration_instructions()));
            }
        }
    }

    // Fallback: check config files + binary availability when no hook files exist yet.
    // This catches hook managers that are configured (e.g. prek.toml exists) and
    // available on PATH, but haven't installed their hooks yet (e.g. `prek install`
    // not yet run). The binary check prevents false positives from stale config files.
    if !saw_hook_file
        && let Some(&manager) = ALL_MANAGERS
            .iter()
            .find(|m| m.has_config(workdir) && m.is_available(workdir))
    {
        tracing::info!(
            "Detected {} config in workdir with binary available (no hook files yet), \
             skipping hook installations",
            manager.name()
        );
        return Some((manager.name(), manager.integration_instructions()));
    }

    // If a config file exists but the binary is not available, log it but proceed
    // with managed mode — the manager is configured but inactive.
    if !saw_hook_file && let Some(&manager) = ALL_MANAGERS.iter().find(|m| m.has_config(workdir)) {
        tracing::info!(
            "Found {} config in workdir but binary is not available, \
             proceeding with GitButler managed hooks",
            manager.name()
        );
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::sync::Mutex;
    use tempfile::TempDir;

    /// Mutex to serialize tests that manipulate the `_GITBUTLER_TEST_BINARY_AVAILABLE`
    /// environment variable. Without this, parallel test threads would race on the
    /// shared env var and produce flaky results.
    static ENV_MUTEX: Mutex<()> = Mutex::new(());

    /// Run a closure with the test binary-availability flag set (simulates prek being in PATH).
    fn with_binary_available<F: FnOnce() -> R, R>(f: F) -> R {
        let _guard = ENV_MUTEX.lock().unwrap();
        // SAFETY: We hold ENV_MUTEX, so no other test thread is reading/writing
        // this env var concurrently.
        unsafe { std::env::set_var("_GITBUTLER_TEST_BINARY_AVAILABLE", "1") };
        let result = f();
        unsafe { std::env::remove_var("_GITBUTLER_TEST_BINARY_AVAILABLE") };
        result
    }

    /// Run a closure with the test binary-availability flag unset (simulates prek NOT in PATH).
    fn with_binary_unavailable<F: FnOnce() -> R, R>(f: F) -> R {
        let _guard = ENV_MUTEX.lock().unwrap();
        // SAFETY: We hold ENV_MUTEX, so no other test thread is reading/writing
        // this env var concurrently.
        unsafe { std::env::remove_var("_GITBUTLER_TEST_BINARY_AVAILABLE") };
        f()
    }

    // ── Content-based detection (strong signal) ────────────────────────

    #[test]
    fn detect_prek_by_generated_comment() {
        let dir = TempDir::new().unwrap();
        let content = r#"#!/bin/sh
# File generated by prek: https://github.com/j178/prek
# ID: 182c10f181da4464a3eec51b83331688

HERE="$(cd "$(dirname "$0")" && pwd)"
PREK="/opt/homebrew/bin/prek"

if [ ! -x "$PREK" ]; then
    PREK="prek"
fi

exec "$PREK" hook-impl --hook-dir "$HERE" --script-version 4 --hook-type=pre-commit -- "$@"
"#;
        let result = detect_hook_manager(content, dir.path());
        assert_eq!(result, Some(KnownManager::Prek));
    }

    #[test]
    fn detect_prek_by_hook_impl_invocation() {
        let dir = TempDir::new().unwrap();
        let content = "#!/bin/sh\nexec prek hook-impl --hook-type=pre-commit -- \"$@\"\n";
        let result = detect_hook_manager(content, dir.path());
        assert_eq!(result, Some(KnownManager::Prek));
    }

    #[test]
    fn content_detection_does_not_require_binary_in_path() {
        let dir = TempDir::new().unwrap();
        let content = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
        // Binary NOT available, but content match should still detect
        with_binary_unavailable(|| {
            let result = detect_hook_manager(content, dir.path());
            assert_eq!(result, Some(KnownManager::Prek));
        });
    }

    // ── Config-based detection (requires binary availability) ──────────

    #[test]
    fn detect_prek_by_config_file_when_binary_available() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();
        with_binary_available(|| {
            let result = detect_hook_manager("#!/bin/sh\necho hello", dir.path());
            assert_eq!(result, Some(KnownManager::Prek));
        });
    }

    #[test]
    fn config_only_does_not_detect_when_binary_unavailable() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();
        with_binary_unavailable(|| {
            let result = detect_hook_manager("#!/bin/sh\necho hello", dir.path());
            assert!(
                result.is_none(),
                "stale config should not trigger detection"
            );
        });
    }

    // ── No detection ──────────────────────────────────────────────────

    #[test]
    fn no_detection_for_plain_user_hook() {
        let dir = TempDir::new().unwrap();
        let content = "#!/bin/sh\necho 'my custom hook'\nexit 0\n";
        let result = detect_hook_manager(content, dir.path());
        assert!(result.is_none());
    }

    #[test]
    fn no_detection_without_config_or_content() {
        let dir = TempDir::new().unwrap();
        let result = detect_hook_manager("", dir.path());
        assert!(result.is_none());
    }

    // ── Priority: content wins over config ─────────────────────────────

    #[test]
    fn content_match_wins_regardless_of_binary_availability() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();
        let prek_content = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
        // Even with binary unavailable, content signature is enough
        with_binary_unavailable(|| {
            let result = detect_hook_manager(prek_content, dir.path());
            assert_eq!(result, Some(KnownManager::Prek));
        });
    }

    // ── detect_hook_manager_in_hooks_dir ───────────────────────────────

    #[test]
    fn hooks_dir_finds_prek_by_content() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        let prek_hook = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
        fs::write(hooks_dir.join("pre-commit"), prek_hook).unwrap();

        let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
        assert!(result.is_some());
        let (name, instructions) = result.unwrap();
        assert_eq!(name, "prek");
        assert!(instructions.contains("but hook pre-commit"));
    }

    #[test]
    fn hooks_dir_returns_none_for_plain_hooks() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        let plain_hook = "#!/bin/sh\necho 'my hook'\n";
        fs::write(hooks_dir.join("pre-commit"), plain_hook).unwrap();

        let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
        assert!(result.is_none());
    }

    #[test]
    fn hooks_dir_ignores_config_fallback_when_plain_hook_exists() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();
        fs::write(
            hooks_dir.join("pre-commit"),
            "#!/bin/sh\necho 'plain hook'\n",
        )
        .unwrap();

        // Config fallback should NOT apply when hook files exist (even with binary available)
        with_binary_available(|| {
            let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
            assert!(result.is_none());
        });
    }

    #[test]
    fn hooks_dir_config_only_fallback_with_binary_available() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();

        with_binary_available(|| {
            let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
            assert!(result.is_some());
            let (name, _) = result.unwrap();
            assert_eq!(name, "prek");
        });
    }

    #[test]
    fn hooks_dir_config_only_fallback_without_binary_returns_none() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();

        with_binary_unavailable(|| {
            let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
            assert!(
                result.is_none(),
                "config-only without binary should not block managed hooks"
            );
        });
    }

    #[test]
    fn hooks_dir_config_only_no_hooks_dir_with_binary() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        // hooks_dir doesn't even exist
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();

        with_binary_available(|| {
            let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
            assert!(result.is_some());
            let (name, _) = result.unwrap();
            assert_eq!(name, "prek");
        });
    }

    #[test]
    fn hooks_dir_config_only_no_hooks_dir_without_binary() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        // hooks_dir doesn't even exist, and binary not available
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();

        with_binary_unavailable(|| {
            let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
            assert!(result.is_none());
        });
    }

    #[test]
    fn hooks_dir_partial_ownership_detects_on_first_match() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        // prek owns pre-commit, but post-checkout is a plain user hook
        let prek_hook = "#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n";
        fs::write(hooks_dir.join("pre-commit"), prek_hook).unwrap();
        fs::write(
            hooks_dir.join("post-checkout"),
            "#!/bin/sh\necho 'user hook'\n",
        )
        .unwrap();

        let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
        assert!(
            result.is_some(),
            "all-or-nothing: prek on any hook → detected"
        );
        assert_eq!(result.unwrap().0, "prek");
    }

    #[test]
    fn hooks_dir_gitbutler_managed_hooks_not_detected_as_external() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        // GitButler's own managed hook should NOT trigger external manager detection
        let gb_hook = "#!/bin/sh\n# GITBUTLER_MANAGED_HOOK_V1\necho 'workspace guard'\n";
        fs::write(hooks_dir.join("pre-commit"), gb_hook).unwrap();

        let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
        assert!(result.is_none());
    }

    // ── Project-local binary detection (.venv/bin, node_modules/.bin) ─

    #[test]
    fn detect_prek_by_config_file_when_binary_in_venv() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();

        // Simulate `uv add --dev prek` by creating .venv/bin/prek
        let venv_bin = dir.path().join(".venv/bin");
        fs::create_dir_all(&venv_bin).unwrap();
        fs::write(venv_bin.join("prek"), "#!/bin/sh\n# mock prek binary").unwrap();

        // Binary not on system PATH, but exists in .venv/bin/
        with_binary_unavailable(|| {
            let result = detect_hook_manager("#!/bin/sh\necho hello", dir.path());
            assert_eq!(
                result,
                Some(KnownManager::Prek),
                "should detect prek via .venv/bin/ when not on system PATH"
            );
        });
    }

    #[test]
    fn detect_prek_by_config_file_when_binary_in_node_modules() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();

        // Simulate `npm add -D @j178/prek` by creating node_modules/.bin/prek
        let nm_bin = dir.path().join("node_modules/.bin");
        fs::create_dir_all(&nm_bin).unwrap();
        fs::write(nm_bin.join("prek"), "#!/bin/sh\n# mock prek binary").unwrap();

        // Binary not on system PATH, but exists in node_modules/.bin/
        with_binary_unavailable(|| {
            let result = detect_hook_manager("#!/bin/sh\necho hello", dir.path());
            assert_eq!(
                result,
                Some(KnownManager::Prek),
                "should detect prek via node_modules/.bin/ when not on system PATH"
            );
        });
    }

    #[test]
    fn hooks_dir_config_only_fallback_with_binary_in_venv() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();
        let venv_bin = dir.path().join(".venv/bin");
        fs::create_dir_all(&venv_bin).unwrap();
        fs::write(venv_bin.join("prek"), "#!/bin/sh").unwrap();

        with_binary_unavailable(|| {
            let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
            assert!(
                result.is_some(),
                "should detect prek via .venv/bin/ fallback"
            );
            assert_eq!(result.unwrap().0, "prek");
        });
    }

    #[test]
    fn hooks_dir_config_only_fallback_with_binary_in_node_modules() {
        let dir = TempDir::new().unwrap();
        let hooks_dir = dir.path().join("hooks");
        fs::create_dir(&hooks_dir).unwrap();

        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();
        let nm_bin = dir.path().join("node_modules/.bin");
        fs::create_dir_all(&nm_bin).unwrap();
        fs::write(nm_bin.join("prek"), "#!/bin/sh").unwrap();

        with_binary_unavailable(|| {
            let result = detect_hook_manager_in_hooks_dir(&hooks_dir, dir.path());
            assert!(
                result.is_some(),
                "should detect prek via node_modules/.bin/ fallback"
            );
            assert_eq!(result.unwrap().0, "prek");
        });
    }

    #[test]
    fn no_detection_when_binary_missing_from_all_locations() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("prek.toml"), "# prek config").unwrap();
        // No .venv/bin/prek, no node_modules/.bin/prek, not on PATH
        with_binary_unavailable(|| {
            let result = detect_hook_manager("#!/bin/sh\necho hello", dir.path());
            assert!(
                result.is_none(),
                "config-only without any binary should not trigger detection"
            );
        });
    }
}
