//! Generate TypeScript type definitions from JSON schemas registered by `#[but_api]` functions.
//!
//! This binary collects all type schemas registered in the `but-api` crate,
//! converts them to TypeScript type definitions, and
//! writes them to a `.d.ts` file.
//!
//! Usage:
//! ```
//!  but-ts --output <path>
//! ```
//!
//!
//! Example:
//! ```
//! but-ts --output packages/but-sdk/generated/types.d.ts
//! ```
//!

use anyhow::bail;
// Link but-api to ensure types are correctly collected.
use but_api as _;
use serde_json::Value;

use std::{
    borrow::Cow,
    collections::{BTreeMap, HashMap},
    fmt::Write,
    path::PathBuf,
};

use but_schemars::SchemarEntry;

fn main() -> anyhow::Result<()> {
    let output_path = parse_args()?;

    // Collect schemas from the but-api schema registry
    let schemas = collect_all_schemas()?;

    eprintln!("Collected {} unique type schemas", schemas.len());

    // Convert schemas to JSON values for processing
    let json_schemas: Vec<(String, serde_json::Value)> = schemas
        .into_iter()
        .filter_map(|(name, schema)| {
            serde_json::to_value(&schema)
                .ok()
                .map(|v| (name.to_string(), v))
        })
        .collect();

    let mut ts_output = String::new();
    writeln!(
        ts_output,
        "// Auto-generated by but-ts. Do not edit manually."
    )?;
    writeln!(
        ts_output,
        "// Generated from JSON schemas registered by #[but_api] functions.\n"
    )?;

    // Sort by name for stable output
    let mut sorted: BTreeMap<&str, &serde_json::Value> = BTreeMap::new();
    for (name, schema) in &json_schemas {
        sorted.insert(name.as_str(), schema);
    }

    // Generate top-level types
    for (name, schema) in &sorted {
        if let Some(desc) = get_description(schema) {
            write!(ts_output, "{}", format_jsdoc(&desc, 0))?;
        }
        let ts_type = schema_to_ts(schema, 0);
        writeln!(ts_output, "export type {name} = {ts_type};\n")?;
    }

    // Write output
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let mut final_output = ts_output.clone();
    if output_path.exists() {
        let existing = std::fs::read_to_string(&output_path)?;
        final_output = format!("{}\n{}", existing, ts_output);
    }

    std::fs::write(&output_path, &final_output)?;
    eprintln!("Written to {}", output_path.display());

    Ok(())
}

struct CollectedSchemarEntry {
    /// The name of the schema getting registered
    pub name: Cow<'static, str>,
    /// The qualified type that was registered
    pub type_name: &'static str,
    /// The location of the register call
    pub registration_location: &'static str,
    /// The actual schema of the type getting registered
    pub schema: schemars::Schema,
}

/// Collect all registered type schemas.
///
/// Returns a list of `(name, schema)` pairs for all registered types.
/// This is used by the `but-ts` tool to produce TypeScript definitions.
fn collect_all_schemas() -> anyhow::Result<Vec<(String, schemars::Schema)>> {
    let mut types = inventory::iter::<SchemarEntry>()
        .map(|s| CollectedSchemarEntry {
            name: (s.name)(),
            type_name: s.type_name,
            registration_location: s.registration_location,
            schema: (s.schema)(),
        })
        .collect::<Vec<_>>();

    // Order by registration location for a stable checking order
    types.sort_by_cached_key(|s| s.registration_location);

    let mut existing_names = HashMap::<&str, &CollectedSchemarEntry>::new();

    for t in &types {
        if let Some(duplicate) = existing_names.get(t.name.as_ref()) {
            bail!(
                "Error when registering schema {} for type {} registered at {}\n\nDuplicate type {} was registered at {}. Consider renaming one of the types with either `#[serde(rename = ...)]` or `#[schemars(rename = ...)]`.\n",
                t.name,
                t.type_name,
                t.registration_location,
                duplicate.type_name,
                duplicate.registration_location
            );
        } else {
            existing_names.insert(t.name.as_ref(), t);
        }
    }

    for t in &types {
        if let Some(obj) = t.schema.as_object()
            && let Some(serde_json::Value::Object(defs)) =
                obj.get("$defs").or_else(|| obj.get("definitions"))
        {
            for (def_name, def_schema) in defs {
                if let Some(entry) = existing_names.get(&def_name.as_ref()) {
                    let entry_schema = entry.schema.clone().to_value();
                    if !root_equals_def(&entry_schema, def_schema, def_name) {
                        bail!(
                            "Error when registering schema {} for type {} registered at {}\n\nThe registered dependent type {} has a different signature than what is expected. This indicates a potential name collision. Consider renaming one of the types with either `#[serde(rename = ...)]` or `#[schemars(rename = ...)]`.\n",
                            t.name,
                            t.type_name,
                            t.registration_location,
                            def_name
                        )
                    }
                } else {
                    bail!(
                        "Error when registering schema {} for type {} registered at {}\n\nMissing dependent type {}. Consider deriving `JsonSchema` on the type and registering it with `register_sdk_type!()`.\n",
                        t.name,
                        t.type_name,
                        t.registration_location,
                        def_name
                    )
                }
            }
        }
    }

    // Order output types by name
    types.sort_by_cached_key(|t| t.name.to_string());

    Ok(types
        .into_iter()
        .map(|s| (s.name.to_string(), s.schema))
        .collect())
}

/// Determines whether a root schema and a reference schema are equal by the
/// definitions of the types.
///
/// The first argument must be a root schema from schemars and the second
/// argument must be a `$defs` schema from schemars.
///
/// Self-referential references are different between root and def schemas - a
/// self referential root schema uses just `#` where as a def schema uses
/// `#/$defs/{type_name}`. To account for this, any value in the root schema
/// that equals `#` is assumed to be `#/$defs/{typename}` when comparing against
/// the def schema.
fn root_equals_def(root_schema: &Value, def_schema: &Value, type_name: &str) -> bool {
    ["properties", "description", "required"]
        .iter()
        .all(|key| root_equals_def_inner(&root_schema[key], &def_schema[key], type_name))
}

fn root_equals_def_inner(root_schema: &Value, def_schema: &Value, type_name: &str) -> bool {
    if let (Some(a), Some(b)) = (root_schema.as_object(), def_schema.as_object()) {
        if a.len() == b.len() {
            a.iter().all(|(ak, av)| {
                b.get(ak)
                    .is_some_and(|bv| root_equals_def(av, bv, type_name))
            })
        } else {
            false
        }
    } else if let (Some(a), Some(b)) = (root_schema.as_array(), def_schema.as_array()) {
        if a.len() == b.len() {
            a.iter()
                .zip(b)
                .all(|(a, b)| root_equals_def(a, b, type_name))
        } else {
            false
        }
    } else if let (Some(a), Some(b)) = (root_schema.as_str(), def_schema.as_str()) {
        if a == b {
            true
        } else {
            // If the root_schema is self-referential, try compare against the
            // name used in a self-referential $def schema.
            a == "#" && format!("#/$defs/{type_name}") == b
        }
    } else {
        root_schema == def_schema
    }
}

fn parse_args() -> anyhow::Result<PathBuf> {
    let mut args = std::env::args().skip(1);
    let mut output = None;
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--output" | "-o" => {
                output = Some(PathBuf::from(args.next().ok_or_else(|| {
                    anyhow::anyhow!("--output requires a path argument")
                })?));
            }
            "--help" | "-h" => {
                eprintln!("Usage: but-ts --output <path>");
                std::process::exit(0);
            }
            other => {
                anyhow::bail!("Unknown argument: {other}");
            }
        }
    }
    output.ok_or_else(|| anyhow::anyhow!("--output is required"))
}

/// Extract the `description` field from a JSON Schema value, if present.
fn get_description(schema: &serde_json::Value) -> Option<String> {
    schema
        .as_object()
        .and_then(|obj| obj.get("description"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
}

/// Format a description string as a JSDoc comment with proper indentation.
fn format_jsdoc(description: &str, indent: usize) -> String {
    let padding = "  ".repeat(indent);
    let lines: Vec<&str> = description.lines().collect();
    if lines.len() == 1 {
        format!("{padding}/** {description} */\n")
    } else {
        let mut out = format!("{padding}/**\n");
        for line in &lines {
            if line.is_empty() {
                out.push_str(&format!("{padding} *\n"));
            } else {
                out.push_str(&format!("{padding} * {line}\n"));
            }
        }
        out.push_str(&format!("{padding} */\n"));
        out
    }
}

/// Convert a JSON Schema (as serde_json::Value) to a TypeScript type string.
fn schema_to_ts(schema: &serde_json::Value, indent: usize) -> String {
    // Handle boolean schemas
    match schema {
        serde_json::Value::Bool(true) => return "any".to_string(),
        serde_json::Value::Bool(false) => return "never".to_string(),
        _ => {}
    }

    let obj = match schema.as_object() {
        Some(o) => o,
        None => return "any".to_string(),
    };

    // Handle $ref
    if let Some(ref_val) = obj.get("$ref")
        && let Some(ref_str) = ref_val.as_str()
    {
        if let Some(type_name) = ref_str
            .strip_prefix("#/$defs/")
            .or_else(|| ref_str.strip_prefix("#/definitions/"))
        {
            return type_name.to_string();
        }
        return "any".to_string();
    }
    // Handle const
    if let Some(const_val) = obj.get("const") {
        return match const_val {
            serde_json::Value::String(s) => format!("\"{}\"", s.replace('"', "\\\"")),
            serde_json::Value::Number(n) => n.to_string(),
            serde_json::Value::Bool(b) => b.to_string(),
            serde_json::Value::Null => "null".to_string(),
            _ => "any".to_string(),
        };
    }

    // Handle enum (string literals)
    if let Some(enum_vals) = obj.get("enum")
        && let Some(arr) = enum_vals.as_array()
    {
        let variants: Vec<String> = arr
            .iter()
            .map(|v| match v {
                serde_json::Value::String(s) => format!("\"{}\"", s.replace('"', "\\\"")),
                serde_json::Value::Number(n) => n.to_string(),
                serde_json::Value::Bool(b) => b.to_string(),
                serde_json::Value::Null => "null".to_string(),
                _ => "any".to_string(),
            })
            .collect();
        return variants.join(" | ");
    }

    // Handle oneOf (discriminated unions)
    if let Some(one_of) = obj.get("oneOf")
        && let Some(arr) = one_of.as_array()
    {
        let variants: Vec<String> = arr.iter().map(|s| schema_to_ts(s, indent)).collect();
        return variants.join(" | ");
    }

    // Handle anyOf
    if let Some(any_of) = obj.get("anyOf")
        && let Some(arr) = any_of.as_array()
    {
        // Special case: anyOf with exactly 2 items where one is null → T | null
        if arr.len() == 2 {
            let is_null: Vec<bool> = arr
                .iter()
                .map(|s| {
                    s.as_object()
                        .and_then(|o| o.get("type"))
                        .and_then(|t| t.as_str())
                        == Some("null")
                })
                .collect();
            if is_null[0] {
                return format!("{} | null", schema_to_ts(&arr[1], indent));
            }
            if is_null[1] {
                return format!("{} | null", schema_to_ts(&arr[0], indent));
            }
        }
        let variants: Vec<String> = arr.iter().map(|s| schema_to_ts(s, indent)).collect();
        return variants.join(" | ");
    }

    // Handle allOf (intersection)
    if let Some(all_of) = obj.get("allOf")
        && let Some(arr) = all_of.as_array()
    {
        let parts: Vec<String> = arr.iter().map(|s| schema_to_ts(s, indent)).collect();
        return parts.join(" & ");
    }

    // Handle union type
    let type_field = obj.get("type");
    if let Some(type_field) = type_field
        && type_field.is_array()
    {
        let type_variants: Vec<String> = type_field
            .as_array()
            .unwrap_or(&vec![])
            .iter()
            .filter_map(|t| t.as_str())
            .map(|t| match t {
                "string" => "string".to_string(),
                "number" | "integer" => "number".to_string(),
                "boolean" => "boolean".to_string(),
                "null" => "null".to_string(),
                "array" => {
                    if let Some(prefix_items) = obj.get("prefixItems")
                        && let Some(arr) = prefix_items.as_array()
                    {
                        let types: Vec<String> =
                            arr.iter().map(|s| schema_to_ts(s, indent)).collect();
                        format!("[{}]", types.join(", "))
                    } else if let Some(items) = obj.get("items") {
                        let item_ty = schema_to_ts(items, indent);
                        format!("Array<{item_ty}>")
                    } else {
                        "Array<any>".to_string()
                    }
                }
                "object" => "Record<string, unknown>".to_string(),
                _ => "any".to_string(),
            })
            .collect();
        return type_variants.join(" | ");
    }

    // Handle type field
    let type_val = type_field.and_then(|t| t.as_str());
    match type_val {
        Some("string") => "string".to_string(),
        Some("number" | "integer") => "number".to_string(),
        Some("boolean") => "boolean".to_string(),
        Some("null") => "null".to_string(),
        Some("array") => {
            if let Some(prefix_items) = obj.get("prefixItems")
                && let Some(arr) = prefix_items.as_array()
            {
                let types: Vec<String> = arr.iter().map(|s| schema_to_ts(s, indent)).collect();
                format!("[{}]", types.join(", "))
            } else if let Some(items) = obj.get("items") {
                let item_ty = schema_to_ts(items, indent);
                format!("Array<{item_ty}>")
            } else {
                "Array<any>".to_string()
            }
        }
        Some("object") => {
            if let Some(props) = obj.get("properties") {
                if let Some(props_obj) = props.as_object() {
                    let required: Vec<String> = obj
                        .get("required")
                        .and_then(|r| r.as_array())
                        .map(|arr| {
                            arr.iter()
                                .filter_map(|v| v.as_str().map(String::from))
                                .collect()
                        })
                        .unwrap_or_default();

                    let next_indent = indent + 1;
                    let padding = "  ".repeat(next_indent);
                    let close_padding = "  ".repeat(indent);

                    let mut fields: Vec<String> = Vec::new();
                    // The map impl with `preserve_order` feature flag is stable
                    // and matches the order properties were declared in rust.
                    for (key, value) in props_obj {
                        let doc = if let Some(desc) = get_description(value) {
                            format_jsdoc(&desc, next_indent)
                        } else {
                            "".to_string()
                        };
                        let ts_type = schema_to_ts(value, next_indent);
                        let optional = if required.contains(key) { "" } else { "?" };
                        fields.push(format!("{doc}{padding}{key}{optional}: {ts_type};"));
                    }

                    if fields.is_empty() {
                        "Record<string, unknown>".to_string()
                    } else {
                        format!("{{\n{}\n{close_padding}}}", fields.join("\n"))
                    }
                } else {
                    "Record<string, unknown>".to_string()
                }
            } else if let Some(additional) = obj.get("additionalProperties") {
                let val_ty = schema_to_ts(additional, indent);
                format!("Record<string, {val_ty}>")
            } else {
                "Record<string, unknown>".to_string()
            }
        }
        _ => {
            // No type field — might have properties directly (implicit object)
            if obj.contains_key("properties") {
                let mut obj_with_type = obj.clone();
                obj_with_type.insert(
                    "type".to_string(),
                    serde_json::Value::String("object".to_string()),
                );
                schema_to_ts(&serde_json::Value::Object(obj_with_type), indent)
            } else {
                "any".to_string()
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use schemars::JsonSchema;
    use serde::Serialize;

    /// Convert a schemars-annotated type to its TypeScript representation.
    fn ts_for<T: JsonSchema>() -> String {
        let schema = schemars::schema_for!(T);
        let json = serde_json::to_value(&schema).unwrap();
        schema_to_ts(&json, 0)
    }

    #[derive(Serialize, JsonSchema)]
    struct ObjectWithTuplesAndArrays {
        simple_array: Vec<String>,
        optional_array: Option<Vec<String>>,
        tuple_array: Vec<(String, i64)>,
        optional_tuple_array: Option<Vec<(String, i64)>>,
        #[expect(clippy::type_complexity)]
        nested_optional_tuple_nested_array: Option<Option<Vec<Vec<(String, i64)>>>>,
        #[expect(clippy::type_complexity)]
        tuple_with_optional_members: Option<Vec<(Option<i64>, Option<Vec<String>>)>>,
    }

    #[test]
    fn object_with_tuples_and_arrays() {
        insta::assert_snapshot!(ts_for::<ObjectWithTuplesAndArrays>(), @"
        {
          simple_array: Array<string>;
          optional_array?: Array<string> | null;
          tuple_array: Array<[string, number]>;
          optional_tuple_array?: Array<[string, number]> | null;
          nested_optional_tuple_nested_array?: Array<Array<[string, number]>> | null;
          tuple_with_optional_members?: Array<[number | null, Array<string> | null]> | null;
        }
        ");
    }
}
