// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about branches, associated with any Git branch.
 */
export type Branch = { 
/**
 * Standard data we want to know about any ref.
 */
refInfo: RefInfo, 
/**
 * More details about the branch.
 */
description: string | null, 
/**
 * Information about possibly ongoing reviews in various forges.
 */
review: Review, };

/**
 * Basic information to know about a reference we store with the metadata system.
 *
 * It allows keeping track of when it changed, but also if we created it initially, a useful
 * bit of information.
 */
export type RefInfo = { 
/**
 * The time of creation, *if we created the reference*.
 */
createdAt: number | null, 
/**
 * The time at which the reference was last modified if we modified it.
 */
updatedAt: number | null, };

/**
 * Metadata about branches, associated with any Git branch.
 */
export type Review = { 
/**
 * The number for the PR that was associated with this branch.
 */
pullRequest: number | null, 
/**
 * A handle to the review created with the GitButler review system.
 */
reviewId: string | null, };
