name: init-env-node
description: Prepare Node.js Environment
runs:
  using: "composite"
  steps:
    - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
      name: Install pnpm
      with:
        cache: true
