[package]
name = "but-meta"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
description = "Database reference metadata maintenance"
publish = false
rust-version.workspace = true

[lib]
doctest = false
test = false

[dependencies]
but-core.workspace = true
but-db.workspace = true

anyhow.workspace = true

gix = { workspace = true, features = ["revision"] }

[dev-dependencies]
but-testsupport.workspace = true

[lints]
workspace = true
