# https://github.com/actions/labeler#create-workflow

name: Label Pull Requests
on:
  pull_request:

jobs:
  labeler:
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: "gitbutlerapp/gitbutler"
      - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v6
        with:
          configuration-path: ".github/pr-labeler.yml"
